import json

danish_strings = [
  "Livets omveje 1",
  "Gå på opdagelse i talemåder og lær om at lykkes, trække sig, fejle og starte forfra.",
  "At lykkes & Målrettet flid",
  "Blind høne, skyde papegøjen, ramme plet og at kaste frugt af sig.",
  "At lykkes",
  "At man kan være heldig at lykkes med noget, selvom man egentlig ikke er særligt dygtig eller har forberedt sig.",
  "At en person, der arbejder i det stille, altid ender med at finde den største belønning.",
  "At man er så stædig, at man stjæler andres hårdt tjente resultater.",
  "At et dårligt syn ofte gør, at man lægger mærke til de helt små detaljer på jorden.",
  "At man er usædvanligt heldig og vinder den helt store gevinst (oftest et godt ægteskab eller drømmejobbet).",
  "At man er så utroligt præcis i sit arbejde, at man kan ramme et meget lille mål.",
  "At man ødelægger noget smukt og sjældent, bare fordi man vil vise sig frem for andre.",
  "At man tager på en lang jagt for at finde den eneste løsning på et svært problem.",
  "At man siger eller gør noget, der er fuldstændig rigtigt og præcist i den givne situation.",
  "At man vinder en stor sum penge i et meget svært og kompliceret spil.",
  "At man ved et uheld rammer et ømt punkt hos en anden og gør dem meget kede af det.",
  "At man skyder til måls og formår at træffe midten af skiven.",
  "At en proces eller opgave forløber helt planmæssigt, nemt og uden nogen form for problemer.",
  "At man har så meget energi, at man kan arbejde hurtigere end alle andre i teamet.",
  "At man sidder urokkeligt fast i en gammel rutine og nægter at prøve nye metoder.",
  "At man vælger at tage toget i stedet for bilen for at undgå trafikken på vejene.",
  "At ens hårde arbejde endelig giver et godt og synligt resultat, som man kan nyde godt af.",
  "At man er et meget generøst menneske, der elsker at dele ud af sine gaver til andre.",
  "At man spilder sine gode idéer på folk, som overhovedet ikke forstår dem.",
  "At man planter et træ i sin have og venter flere år på at kunne høste fra det.",
  "Mental & Handlingsretræte",
  "At stikke piben ind, trække i land, slå bak og kaste håndklædet i ringen.",
  "Retræte",
  "At man bliver forsigtig og trækker sig tilbage for at vurdere en situation, før man gør mere.",
  "At man lytter ekstremt godt efter, hvad andre fortæller en, så man kan hjælpe dem bedst muligt.",
  "At man lukker sig fuldstændig inde i sig selv og nægter at tale med sine venner.",
  "At man tager tykt tøj på for at beskytte sig mod kulden udenfor.",
  "At man dæmper sig, bliver mindre påståelig og bøjer sig, fordi man indser, at man tager fejl.",
  "At man kommer med en fantastisk idé, som løser problemet for hele gruppen.",
  "At man stjæler opmærksomheden fra en anden, netop som de skal til at tale.",
  "At man pakker sine ting sammen og forbereder sig på at tage hjem fra arbejde.",
  "At man ændrer mening eller trækker en tidligere påstand tilbage for at undgå en konflikt.",
  "At man redder et andet menneske ud af en meget farlig situation.",
  "At man nægter at betale sin gæld tilbage til en ven, der ellers har hjulpet en.",
  "At man fortøjrer sin båd solidt til molen efter en lang dag på havet.",
  "At man bremser op, fortryder sin handling og trækker sig tilbage fra det, man var i gang med.",
  "At man slår et stort og flot brød op, som man deler med hele familien.",
  "At man slår en anden person i ryggen for at få sin vilje trumfet igennem.",
  "At man skifter gear i bilen for at kunne køre baglæns ud af en parkeringsplads.",
  "At man giver helt op og erkender sit nederlag, fordi situationen er blevet for svær at klare.",
  "At man smider sine bekymringer væk og endelig begynder at nyde livet i fulde drag.",
  "At man kaster sit skrald i naturen i stedet for at rydde ordentligt op efter sig selv.",
  "At man er færdig med at tage bad og lægger håndklædet til vask.",
  "Fejltrin & Kollaps",
  "At træde i spinaten, gå i baglås, stå med håret i postkassen og gå ned med flaget.",
  "At man kommer til at sige eller gøre noget dumt, der gør andre flove eller skaber en pinlig situation.",
  "At man tager ud i naturen for at samle sunde urter og grøntsager til aftensmaden.",
  "At man ødelægger andres hårde arbejde med vilje, fordi man er misundelig.",
  "At man tager sine gamle sko på, fordi det regner og er mudret udenfor.",
  "At man fuldstændig mister evnen til at tænke klart eller handle, ofte fordi man er stresset eller presset.",
  "At man sikrer sit hus så godt, at ingen tyve nogensinde kan bryde ind.",
  "At man låser en anden person inde på et værelse for at straffe dem.",
  "At man glemmer sin nøgle og må vente på at en låsesmed kommer og hjælper.",
  "At man påtager sig en opgave eller et ansvar, som er alt for stort og svært til, at man kan klare det.",
  "At man bager så meget brød, at man kan invitere hele nabolaget til en stor fest.",
  "At man spiser så meget mad, at man bliver frygteligt syg og kaster op.",
  "At man lærer at ælte dejen rigtigt for at få luftige og lækre boller.",
  "At man er havnet i en rigtig ærgerlig og uforskyldt knibe, hvor man står tilbage som taberen.",
  "At man modtager et fantastisk kærestebrev, som får en til at rødme af glæde.",
  "At man stjæler andres post for at finde hemmeligheder om dem.",
  "At man går ud for at hente avisen, mens det blæser kraftigt udenfor.",
  "At man bryder helt sammen af stress eller sygdom og simpelthen ikke har energi til mere.",
  "At man sænker flaget ved solnedgang som en smuk og ærefuld tradition.",
  "At man nægter at fejre andres fødselsdag og i stedet bliver sur over deres gaver.",
  "At man pakker flagstangen væk for vinteren for at beskytte den mod storm.",
  "Starte på en frisk",
  "At begynde på en frisk, rejse sig ved det træ man er faldet ved, og op på hesten igen.",
  "Starte igen",
  "At man lægger fortidens problemer bag sig og starter forfra med fornyet energi.",
  "At man bager et helt friskt og lækkert brød til at byde sine gæster velkommen.",
  "At man glemmer alle sine gamle venner for kun at bruge tid sammen med nye.",
  "At man tager ud i skoven tidligt om morgenen for at trække vejret i den kølige vind.",
  "At man overvinder sit nederlag ved at prøve igen samme sted eller med samme opgave, hvor det gik galt.",
  "At man planter et nyt og stærkt træ for hvert lille problem man løser i hverdagen.",
  "At man nægter at gå væk fra et sted, hvor man er faldet, selvom man fryser.",
  "At man tager ud for at fælde brænde i skoven, efter det har stormet kraftigt.",
  "At man pludselig ændrer sin måde at gøre tingene på og tager fat med fornyet beslutsomhed.",
  "At man hjælper en anden med at spise, fordi de ikke selv har kræfter til det.",
  "At man kaster sit bestik fra sig i vrede, fordi man ikke kan lide den mad der serveres.",
  "At man øver sig i at spise med venstre hånd, selvom man normalt er højrehåndet.",
  "At man genoptager sit hårde arbejde uden at klage, efter man har holdt pause eller mødt modgang.",
  "At man strikker varme handsker til sine venner, når det begynder at blive vinter.",
  "At man gemmer sine hænder, fordi man ikke gider at hjælpe til med det hårde arbejde.",
  "At man tager en tyk jakke og hue på, fordi man skal ud og skovle sne.",
  "At man hurtigt prøver igen efter et nederlag, så man ikke når at blive bange for at fejle.",
  "At man vinder et flot trofæ i en stor ridekonkurrence efter lang tids træning.",
  "At man presser et stakkels dyr alt for hårdt, selvom det er meget træt.",
  "At man tager ud på en rolig ridetur i skoven for at nyde det gode vejr.",
  "Forberedelse",
  "Mental parathed & beslutning",
  "At tage skeen i den anden hånd",
  "Målrettet flid & resultat",
  "Retræte i handling & handlingsskift",
  "At ramme plet",
  "At kaste håndklædet i ringen",
  "Succes",
  "Fejltrin & procesblokering",
  "At træde i spinaten",
  "At begynde på en frisk",
  "Fejltrin",
  "Start Igen",
  "Fra forberedelse til handling",
  "At komme op på hesten igen",
  "At stikke piben ind",
  "Giv Op",
  "Livets omveje 2",
  "Udforsk talemåder om sundhed, sygdom, kollaps og restitution.",
  "Forebyggelse & Sundhed",
  "At holde lægen fra døren, frisk som en fisk, strut af sundhed osv.",
  "Man gør gode ting for at holde sig sund og stærk, så man har en masse energi i hverdagen og ikke bliver syg.",
  "Gode, sunde vaner i hverdagen beskytter dig generelt mod at blive syg.",
  "At bruge naturens egen medicin, når man har brug for at kurere små skavanker.",
  "At have let ved at blive rask igen, hvis man først er blevet ramt af en virus.",
  "At spise en meget varieret kost for at opbygge store og stærke muskler.",
  "At have en utrolig stærk krop og næsten aldrig være syg.",
  "At have rigtig god kondition, fordi man dyrker meget hård motion.",
  "At have et positivt sind, som gør det nemt at forblive glad i modgang.",
  "At have spist en meget sund og nærende morgenmad, der giver energi.",
  "At føle sig helt rask, vågen og fuld af god, frisk energi.",
  "At elske at bade i koldt vand for at styrke sit hjerte og sit kredsløb.",
  "At have en meget ren og sund hud, fordi man drikker masser af vand.",
  "At være dygtig til at slappe af og finde indre ro i en travl hverdag.",
  "At se så sund og rask ud, at andre meget tydeligt kan se det på én.",
  "At føle en stor indre ro, fordi man ved, at man lever et sundt liv.",
  "At have overvundet en lang sygdom og endelig være erklæret helt rask.",
  "At være meget stolt af sig selv, fordi man motionerer hver eneste dag.",
  "At føle sig rigtig godt tilpas og være i en situation, man nyder meget.",
  "At føle sig enormt stærk i kroppen, lige efter man har trænet hårdt.",
  "At være den person, der altid inspirerer andre til at leve sundt og godt.",
  "At være helt fri for smerter i kroppen, fordi man har hvilet sig nok.",
  "Begyndende svækkelse & Inkubation",
  "At ligne en hængt kat, at have bly i benene osv.",
  "Man mærker de allerførste tegn på, at man er træt, og man føler sig ikke helt frisk og rask længere.",
  "At føle sig meget svag og træt i kroppen uden helt at vide hvorfor.",
  "At have voldsomme smerter i benene efter at have stået op hele dagen.",
  "At være utrolig tung i hovedet, fordi man har sovet for meget i weekenden.",
  "At bryde fuldstændig sammen og slet ikke kunne rejse sig fra sengen.",
  "At være meget uoplagt, mangle energi og se lidt trist ud.",
  "At have en slem forkølelse, der gør det svært at trække vejret normalt.",
  "At være så totalt udmattet, at man pludselig besvimer midt på gaden.",
  "At have overvundet en svær tid og nu endelig kunne puste lidt ud.",
  "At se meget træt, elendig og medtaget ud, så alle kan se, at man har det skidt.",
  "At være vred og irriteret over en lille ting, der lige er gået galt på arbejdet.",
  "At have sovet rigtig dårligt en enkelt nat, fordi det har været for varmt.",
  "At være meget klodset og hele tiden tabe ting på gulvet, fordi man har travlt.",
  "At føle sig lidt sløj og småsyg, så man ikke kan præstere sit allerbedste.",
  "At føle sig enormt stresset over en opgave, man ikke kan finde ud af.",
  "At være kommet sig over en sygdom, men stadig mangle den sidste energi.",
  "At have mistet absolut alle kræfter, så man overhovedet ikke kan arbejde mere.",
  "At føle sig ekstremt tung og træt i kroppen, så det er svært overhovedet at bevæge sig.",
  "At have trænet så meget, at ens benmuskler er vokset og blevet meget stærke.",
  "At føle sig helt låst fast i en svær mental beslutning, som man ikke kan træffe.",
  "At have meget let ved at falde, fordi man har dårlig balance og er lidt svimmel.",
  "Gradvis svækkelse & Det akutte kollaps",
  "At være mat i sokkerne, at gå helt ned med flaget osv.",
  "Man mister alle sine kræfter, og til sidst kan man slet ikke mere, så kroppen tvinger én til at stoppe helt.",
  "At bryde fuldstændig sammen af træthed og overbelastning, så man må give op.",
  "At mærke en langsom og let faldende energi i løbet af en meget lang arbejdsdag.",
  "At blive ramt af en lille smule stress, som forsvinder helt efter et par dages ro.",
  "At være den i firmaet, der altid tager de sværeste opgaver på sine skuldre.",
  "At falde om eller kollapse helt akut, fordi kroppen simpelthen ikke kan mere.",
  "At få det stille og roligt dårligere over en meget lang periode på flere måneder.",
  "At gemme sig for sine problemer ved at blive hjemme i sengen hele dagen lang.",
  "At slappe af på sofaen efter en lang og udmattende arbejdsuge.",
  "Mental restitution & Fysisk genrejsning",
  "At puste ud, at komme til hægterne igen osv.",
  "Man får det langsomt bedre efter en svær tid, og man samler ny energi, så man er klar til at starte forfra.",
  "At slappe helt af i kroppen og lade op efter en hård eller krævende situation.",
  "At have svært ved at få luft efter at have løbet alt for hurtigt.",
  "At være nødt til at sove hele dagen, fordi man er blevet alvorligt syg.",
  "At ignorere sin træthed og fortsætte med at arbejde endnu hårdere.",
  "At få sine kræfter og sit helbred langsomt tilbage efter at have været syg.",
  "At bruge medicin til at blive rask hurtigt, så man ikke misser arbejdet.",
  "At bryde sammen af stress, fordi man har prøvet at klare alt for meget.",
  "At have en fast rutine med at spise meget sundt og træne hver dag.",
  "At blive fuldstændig rask og klar igen efter at have ligget syg i sengen.",
  "At rejse sig alt for hurtigt op, så man føler sig en smule svimmel.",
  "At mærke de allerførste tegn på, at en forkølelse er ved at ramme én.",
  "At nægte at acceptere at man er syg, selvom man har høj feber.",
  "At overvinde sit nederlag ved at prøve igen samme sted, hvor det gik galt.",
  "At tage ud i naturen for at få frisk luft og rense sine tanker.",
  "At lade andre mennesker hjælpe én, når man ikke selv har flere kræfter.",
  "At stoppe helt med at prøve, fordi risikoen for at fejle igen er for stor.",
  "At mærke at tingene går godt igen, og at man får ny energi og succes.",
  "At mærke et pludseligt fald i kropstemperaturen, så man begynder at fryse.",
  "At blive presset af alt for høje forventninger fra de mennesker omkring én.",
  "At tage en pause væk fra det hele og rejse langt væk på ferie.",
  "Forebyggelse",
  "Overbelastning",
  "Svækkelse",
  "At presse sig selv enormt hårdt ved at arbejde for meget og sove for lidt.",
  "Restitution",
  "Kollaps",
  "At blive meget begejstret for et nyt projekt og bruge absolut al sin tid på det.",
  "At føle sig enormt stærk, fordi man dyrker hård motion både morgen og aften.",
  "At være meget opmærksom på at få løst alle sine problemer hurtigst muligt.",
  "At være den i firmaet, der altid tager de allersværeste opgaver på sine skuldre.",
  "At have enormt svært ved at få luft efter at have løbet alt for hurtigt."
]

translated = {}
import urllib.request
import urllib.parse
for s in danish_strings:
    translated[s] = "Трансляция" # I will do it with the LLM. Wait, if I do this I won't get it fast.

