const fs = require('fs');

const file = '/Users/mikaelfabrin/Documents/App-antigravity/Gratisapp/src/utils/translations.js';
let content = fs.readFileSync(file, 'utf8');

const t = {
  "Brug Paraplyen (Det) om den generelle tilstand eller vejret.<br>Brug Pilen (Der) om et specifikt punkt eller en placering.": {
    da: "Brug Paraplyen (Det) om den generelle tilstand eller vejret.<br>Brug Pilen (Der) om et specifikt punkt eller en placering.",
    en: "Use the Umbrella (Det) for general conditions or weather.<br>Use the Arrow (Der) for a specific point or location.",
    de: "Benutze den Regenschirm (Det) für allgemeine Bedingungen oder das Wetter.<br>Benutze den Pfeil (Der) für einen bestimmten Punkt oder Ort.",
    ar: "استخدم المظلة (Det) للظروف العامة أو الطقس.<br>استخدم السهم (Der) لنقطة أو موقع محدد.",
    es: "Usa el Paraguas (Det) para condiciones generales o el clima.<br>Usa la Flecha (Der) para un punto o ubicación específica.",
    fa: "برای شرایط کلی یا آب و هوا از چتر (Det) استفاده کنید.<br>برای یک نقطه یا مکان خاص از فلش (Der) استفاده کنید.",
    ku: "Sîwanê (Det) ji bo rewşên giştî an hewayê bikar bînin.<br>Tîrê (Der) ji bo xalek an cîhek diyarkirî bikar bînin.",
    ne: "सामान्य अवस्था वा मौसमको लागि छाता (Det) प्रयोग गर्नुहोस्।<br>विशिष्ट बिन्दु वा स्थानको लागि तीर (Der) प्रयोग गर्नुहोस्।",
    ps: "د عمومي شرایطو یا هوا لپاره چترۍ (Det) وکاروئ.<br>د یو ځانګړي نقطې یا موقعیت لپاره تیر (Der) وکاروئ.",
    pt: "Use o Guarda-chuva (Det) para condições gerais ou clima.<br>Use a Seta (Der) para um ponto ou local específico.",
    ru: "Используйте Зонт (Det) для общих условий или погоды.<br>Используйте Стрелку (Der) для конкретной точки или места.",
    th: "ใช้ร่ม (Det) สำหรับสภาพทั่วไปหรือสภาพอากาศ<br>ใช้ลูกศร (Der) สำหรับจุดหรือสถานที่เฉพาะ",
    tr: "Genel durumlar veya hava durumu için Şemsiyeyi (Det) kullanın.<br>Belirli bir nokta veya konum için Oku (Der) kullanın.",
    uk: "Використовуйте Парасольку (Det) для загальних умов або погоды.<br>Використовуйте Стрілку (Der) для конкретної точки або місця.",
    ur: "عام حالات یا موسم کے لیے چھتری (Det) کا استعمال کریں۔<br>کسی مخصوص نقطہ یا مقام کے لیے تیر (Der) کا استعمال کریں۔",
    vi: "Sử dụng Ô (Det) cho các điều kiện chung hoặc thời tiết.<br>Sử dụng Mũi tên (Der) cho một điểm hoặc vị trí cụ thể.",
    zh: "在一般情况或天气中使用雨伞 (Det)。<br>对于特定点或位置，请使用箭头 (Der)。"
  },
  "Både \"det\" og \"der\" kan ofte bruges, afhængigt af hvad du vil fokusere på!": {
    da: "Både \"det\" og \"der\" kan ofte bruges, afhængigt af hvad du vil fokusere på!",
    en: "Both \"det\" and \"der\" can often be used, depending on what you want to focus on!",
    de: "Sowohl \"det\" als auch \"der\" können oft verwendet werden, je nachdem, worauf Sie sich konzentrieren möchten!",
    ar: "غالبًا ما يمكن استخدام كل من \"det\" و \"der\" ، اعتمادًا على ما تريد التركيز عليه!",
    es: "¡Tanto \"det\" como \"der\" a menudo se pueden usar, dependiendo de en qué quieras enfocarte!",
    fa: "بسته به اینکه می‌خواهید روی چه چیزی تمرکز کنید، اغلب می‌توان از هر دو «det» و «der» استفاده کرد!",
    ku: "Bi gelemperî hem \"det\" û hem jî \"der\" dikarin werin bikar anîn, li gorî ya ku hûn dixwazin balê bikişînin!",
    ne: "तपाईं केमा फोकस गर्न चाहनुहुन्छ भन्ने आधारमा, प्रायः \"det\" र \"der\" दुवै प्रयोग गर्न सकिन्छ!",
    ps: "ډیری وختونه دواړه \"det\" او \"der\" کارول کیدی شي ، پدې پورې اړه لري چې تاسو څه تمرکز کول غواړئ!",
    pt: "Tanto \"det\" quanto \"der\" costumam ser usados, dependendo no que você quer focar!",
    ru: "Часто можно использовать как «det», так и «der», в зависимости от того, на чем вы хотите сосредоточиться!",
    th: "บ่อยครั้งที่สามารถใช้ได้ทั้ง \"det\" และ \"der\" ขึ้นอยู่กับว่าคุณต้องการเน้นอะไร!",
    tr: "Neye odaklanmak istediğinize bağlı olarak genellikle hem \"det\" hem de \"der\" kullanılabilir!",
    uk: "Часто можна використовувати як «det», так і «der», залежно від того, на чому ви хочете зосередитися!",
    ur: "آپ کس چیز پر توجہ مرکوز کرنا چاہتے ہیں اس پر منحصر ہے کہ اکثر \"det\" اور \"der\" دونوں استعمال کیے جا سکتے ہیں!",
    vi: "Cả \"det\" và \"der\" thường có thể được sử dụng, tùy thuộc vào điều bạn muốn tập trung vào!",
    zh: "“det”和“der”通常都可以使用，具体取决于您想要关注的内容！"
  },
  "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle tilstand og vejret.<br><i>(Tip: 'Der' er også korrekt, hvis du fokuserer på placeringen 'udenfor').</i>": {
    da: "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle tilstand og vejret.<br><i>(Tip: 'Der' er også korrekt, hvis du fokuserer på placeringen 'udenfor').</i>",
    en: "Correct! ☂️ Umbrella: You focus on the general condition and the weather.<br><i>(Tip: 'Der' is also correct if you focus on the location 'outside').</i>",
    de: "Richtig! ☂️ Regenschirm: Du konzentrierst dich auf den allgemeinen Zustand und das Wetter.<br><i>(Tipp: 'Der' ist auch richtig, wenn du dich auf den Ort 'draußen' konzentrierst).</i>",
    ar: "صحيح! ☂️ مظلة: أنت تركز على الحالة العامة والطقس.<br><i>(نصيحة: 'Der' صحيح أيضًا إذا كنت تركز على الموقع 'بالخارج').</i>",
    es: "¡Correcto! ☂️ Paraguas: Te enfocas en la condición general y el clima.<br><i>(Consejo: 'Der' también es correcto si te enfocas en la ubicación 'afuera').</i>",
    fa: "درسته! ☂️ چتر: شما روی وضعیت کلی و آب و هوا تمرکز می کنید.<br><i>(نکته: 'Der' نیز در صورت تمرکز بر روی مکان 'بیرون' صحیح است).</i>",
    ku: "Rast e! ☂️ Sîwan: Hûn balê dikişînin ser rewşa giştî û hewayê.<br><i>(Serişte: 'Der' jî rast e heke hûn balê bikişînin ser cîhê 'derve').</i>",
    ne: "सहि हो! ☂️ छाता: तपाईं सामान्य अवस्था र मौसममा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: यदि तपाईं 'बाहिर' स्थानमा ध्यान केन्द्रित गर्नुहुन्छ भने 'Der' पनि सही छ)।</i>",
    ps: "سمه ده! ☂️ چترۍ: تاسو عمومي حالت او هوا ته پام کوئ.<br><i>(اشاره: 'Der' هم سم دی که تاسو 'بهر' موقعیت ته پام کوئ).</i>",
    pt: "Correto! ☂️ Guarda-chuva: Você foca na condição geral e no clima.<br><i>(Dica: 'Der' também está correto se você focar na localização 'lá fora').</i>",
    ru: "Правильно! ☂️ Зонт: Вы сосредотачиваетесь на общем состоянии и погоде.<br><i>(Подсказка: «Der» также правильно, если вы сосредотачиваетесь на месте «снаружи»).</i>",
    th: "ถูกต้อง! ☂️ ร่ม: คุณเน้นที่สภาพทั่วไปและสภาพอากาศ<br><i>(คำแนะนำ: 'Der' ก็ถูกต้องเช่นกัน หากคุณเน้นที่สถานที่ 'ข้างนอก')</i>",
    tr: "Doğru! ☂️ Şemsiye: Genel duruma ve hava durumuna odaklanıyorsunuz.<br><i>(İpucu: 'dışarısı' konumuna odaklanırsanız 'Der' de doğrudur).</i>",
    uk: "Правильно! ☂️ Парасолька: Ви зосереджуєтесь на загальному стані та погоді.<br><i>(Підказка: «Der» також правильне, якщо ви зосереджуєтесь на місці «зовні»).</i>",
    ur: "بالکل ٹھیک! ☂️ چھتری: آپ عام حالت اور موسم پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Der' بھی صحیح ہے اگر آپ باہر کے مقام پر توجہ مرکوز کرتے ہیں)۔</i>",
    vi: "Chính xác! ☂️ Ô: Bạn tập trung vào điều kiện chung và thời tiết.<br><i>(Mẹo: 'Der' cũng đúng nếu bạn tập trung vào vị trí 'bên ngoài').</i>",
    zh: "正确！ ☂️ 雨伞：您关注一般情况和天气。<br><i>（提示：如果您关注位置“外面”，“Der”也是正确的）。</i>"
  },
  "Rigtigt! 🎯 Pil: Du fokuserer på placeringen udenfor.<br><i>(Tip: 'Det' er også meget almindeligt, da det handler om vejret generelt).</i>": {
    da: "Rigtigt! 🎯 Pil: Du fokuserer på placeringen udenfor.<br><i>(Tip: 'Det' er også meget almindeligt, da det handler om vejret generelt).</i>",
    en: "Correct! 🎯 Arrow: You focus on the location outside.<br><i>(Tip: 'Det' is also very common as it is about the weather in general).</i>",
    de: "Richtig! 🎯 Pfeil: Du konzentrierst dich auf den Ort draußen.<br><i>(Tipp: 'Det' ist auch sehr verbreitet, da es im Allgemeinen um das Wetter geht).</i>",
    ar: "صحيح! 🎯 السهم: أنت تركز على الموقع بالخارج.<br><i>(نصيحة: 'Det' شائع جدًا أيضًا لأنه يتعلق بالطقس بشكل عام).</i>",
    es: "¡Correcto! 🎯 Flecha: Te enfocas en la ubicación de afuera.<br><i>(Consejo: 'Det' también es muy común ya que se trata del clima en general).</i>",
    fa: "درسته! 🎯 فلش: شما روی مکان بیرون تمرکز می کنید.<br><i>(نکته: 'Det' نیز بسیار رایج است زیرا به طور کلی در مورد آب و هوا است).</i>",
    ku: "Rast e! 🎯 Tîr: Hûn balê dikişînin ser cihê derve.<br><i>(Serişte: 'Det' di heman demê de pir gelemperî ye ji ber ku ew bi gelemperî li ser hewayê ye).</i>",
    ne: "सहि हो! 🎯 तीर: तपाईं बाहिरको स्थानमा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: 'Det' पनि धेरै सामान्य छ किनकि यो सामान्यतया मौसमको बारेमा हो)।</i>",
    ps: "سمه ده! 🎯 تیر: تاسو بهر موقعیت ته پام کوئ.<br><i>(اشاره: 'Det' هم خورا عام دی ځکه چې دا په عمومي ډول د هوا په اړه دی).</i>",
    pt: "Correto! 🎯 Seta: Você foca no local lá fora.<br><i>(Dica: 'Det' também é muito comum, pois se trata do clima em geral).</i>",
    ru: "Правильно! 🎯 Стрелка: Вы сосредотачиваетесь на месте снаружи.<br><i>(Подсказка: «Det» также очень распространено, поскольку речь идет о погоде в целом).</i>",
    th: "ถูกต้อง! 🎯 ลูกศร: คุณเน้นที่สถานที่ข้างนอก<br><i>(คำแนะนำ: 'Det' ก็เป็นเรื่องธรรมดามากเช่นกัน เนื่องจากเกี่ยวกับสภาพอากาศโดยทั่วไป)</i>",
    tr: "Doğru! 🎯 Ok: Dışarıdaki konuma odaklanıyorsunuz.<br><i>(İpucu: 'Det' de genel olarak hava durumu ile ilgili olduğu için çok yaygındır).</i>",
    uk: "Правильно! 🎯 Стрілка: Ви зосереджуєтесь на місці зовні.<br><i>(Підказка: «Det» також дуже поширене, оскільки йдеться про погоду в цілому).</i>",
    ur: "بالکل ٹھیک! 🎯 تیر: آپ باہر کے مقام پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Det' بھی بہت عام ہے کیونکہ یہ عام طور پر موسم کے بارے میں ہے)۔</i>",
    vi: "Chính xác! 🎯 Mũi tên: Bạn tập trung vào vị trí bên ngoài.<br><i>(Mẹo: 'Det' cũng rất phổ biến vì nó nói về thời tiết nói chung).</i>",
    zh: "正确！ 🎯 箭头：您关注外面的位置。<br><i>（提示：“Det”也很常见，因为它是关于一般天气的）。</i>"
  },
  "Tænk på Pilen. Vi peger på en helt bestemt fysisk ting (kufferten) på en specifik placering (gulvet).": {
    da: "Tænk på Pilen. Vi peger på en helt bestemt fysisk ting (kufferten) på en specifik placering (gulvet).",
    en: "Think of the Arrow. We point to a very specific physical thing (the suitcase) in a specific location (the floor).",
    de: "Denke an den Pfeil. Wir weisen auf eine ganz bestimmte physische Sache (den Koffer) an einem bestimmten Ort (dem Boden) hin.",
    ar: "فكر في السهم. نحن نشير إلى شيء مادي محدد للغاية (الحقيبة) في مكان معين (الأرضية).",
    es: "Piensa en la Flecha. Señalamos una cosa física muy específica (la maleta) en una ubicación específica (el piso).",
    fa: "به فلش فکر کنید. ما به یک چیز فیزیکی بسیار خاص (چمدان) در یک مکان خاص (کف) اشاره می کنیم.",
    ku: "Tîrê bifikirin. Em balê dikişînin ser tiştek laşî ya pir diyarkirî (valîz) li cîhek taybetî (erd).",
    ne: "तीरको बारेमा सोच्नुहोस्। हामी एक विशेष स्थान (भुइँ) मा एक धेरै विशिष्ट भौतिक कुरा (सुटकेस) लाई औंल्याउँदैछौं।",
    ps: "د تیر په اړه فکر وکړئ. موږ په یو ځانګړي ځای (پوړ) کې یو خورا ځانګړي فزیکي شی (سوکیس) ته اشاره کوو.",
    pt: "Pense na Seta. Apontamos para uma coisa física muito específica (a mala) num local específico (o chão).",
    ru: "Подумайте о Стрелке. Мы указываем на конкретную физическую вещь (чемодан) в определенном месте (на полу).",
    th: "นึกถึงลูกศร เราชี้ไปที่สิ่งของทางกายภาพที่เฉพาะเจาะจงมาก (กระเป๋าเดินทาง) ในตำแหน่งเฉพาะ (พื้น)",
    tr: "Oku düşünün. Belirli bir konumdaki (zemin) çok belirli bir fiziksel nesneyi (bavul) işaret ediyoruz.",
    uk: "Подумайте про Стрілку. Ми вказуємо на конкретну фізичну річ (валізу) у певному місці (на підлозі).",
    ur: "تیر کے بارے میں سوچیں۔ ہم ایک مخصوص جگہ (فرش) پر ایک مخصوص جسمانی چیز (سوٹ کیس) کی طرف اشارہ کر رہے ہیں۔",
    vi: "Hãy nghĩ về Mũi tên. Chúng tôi chỉ vào một vật thể vật lý rất cụ thể (vali) ở một vị trí cụ thể (sàn nhà).",
    zh: "想想箭头。我们指向特定位置（地板）上非常特定的实物（手提箱）。"
  },
  "Rigtigt! 🎯 Pil: Vi peger på en specifik ting på en specifik placering. Her kan man KUN sige 'der'.": {
    da: "Rigtigt! 🎯 Pil: Vi peger på en specifik ting på en specifik placering. Her kan man KUN sige 'der'.",
    en: "Correct! 🎯 Arrow: We point to a specific thing in a specific location. Here you can ONLY say 'der'.",
    de: "Richtig! 🎯 Pfeil: Wir weisen auf eine bestimmte Sache an einem bestimmten Ort hin. Hier kann man NUR 'der' sagen.",
    ar: "صحيح! 🎯 السهم: نحن نشير إلى شيء محدد في مكان محدد. هنا يمكنك فقط أن تقول 'der'.",
    es: "¡Correcto! 🎯 Flecha: Señalamos una cosa específica en una ubicación específica. Aquí SOLO puedes decir 'der'.",
    fa: "درسته! 🎯 فلش: ما به یک چیز خاص در یک مکان خاص اشاره می کنیم. در اینجا شما فقط می توانید 'der' بگویید.",
    ku: "Rast e! 🎯 Tîr: Em tiştek diyarkirî li cîhek diyarkirî nîşan didin. Li vir hûn dikarin TENÊ bibêjin 'der'.",
    ne: "सहि हो! 🎯 तीर: हामी एक निश्चित स्थानमा एक विशेष कुरा औंल्याउँछौं। यहाँ तपाईं केवल 'der' भन्न सक्नुहुन्छ।",
    ps: "سمه ده! 🎯 تیر: موږ په یو ځانګړي ځای کې ځانګړي شی ته اشاره کوو. دلته تاسو یوازې ویلای شئ 'der'.",
    pt: "Correto! 🎯 Seta: Apontamos para uma coisa específica em um local específico. Aqui você SÓ pode dizer 'der'.",
    ru: "Правильно! 🎯 Стрелка: Мы указываем на конкретную вещь в определенном месте. Здесь можно сказать ТОЛЬКО «der».",
    th: "ถูกต้อง! 🎯 ลูกศร: เราชี้ไปที่สิ่งเฉพาะเจาะจงในตำแหน่งเฉพาะ ที่นี่คุณพูดได้แค่ 'der' เท่านั้น",
    tr: "Doğru! 🎯 Ok: Belirli bir konumdaki belirli bir şeye işaret ediyoruz. Burada SADECE 'der' diyebilirsiniz.",
    uk: "Правильно! 🎯 Стрілка: Ми вказуємо на конкретну річ у певному місці. Тут можна сказати ТІЛЬКИ «der».",
    ur: "بالکل ٹھیک! 🎯 تیر: ہم ایک مخصوص مقام پر کسی مخصوص چیز کی طرف اشارہ کرتے ہیں۔ یہاں آپ صرف 'der' کہہ سکتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Chúng tôi chỉ vào một vật cụ thể ở một vị trí cụ thể. Ở đây bạn CHỈ có thể nói 'der'.",
    zh: "正确！ 🎯 箭头：我们指向特定位置的特定事物。这里你只能说“der”。"
  },
  "Rigtigt! ☂️ Paraply: Du fokuserer på stuens generelle tilstand.<br><i>(Tip: 'Der' er også korrekt, hvis du fokuserer på placeringen 'herinde').</i>": {
    da: "Rigtigt! ☂️ Paraply: Du fokuserer på stuens generelle tilstand.<br><i>(Tip: 'Der' er også korrekt, hvis du fokuserer på placeringen 'herinde').</i>",
    en: "Correct! ☂️ Umbrella: You focus on the living room's general condition.<br><i>(Tip: 'Der' is also correct if you focus on the location 'in here').</i>",
    de: "Richtig! ☂️ Regenschirm: Du konzentrierst dich auf den allgemeinen Zustand des Wohnzimmers.<br><i>(Tipp: 'Der' ist auch richtig, wenn du dich auf den Ort 'hier drin' konzentrierst).</i>",
    ar: "صحيح! ☂️ مظلة: أنت تركز على الحالة العامة لغرفة المعيشة.<br><i>(نصيحة: 'Der' صحيح أيضًا إذا كنت تركز على الموقع 'هنا').</i>",
    es: "¡Correcto! ☂️ Paraguas: Te enfocas en la condición general de la sala.<br><i>(Consejo: 'Der' también es correcto si te enfocas en la ubicación 'aquí adentro').</i>",
    fa: "درسته! ☂️ چتر: شما روی وضعیت کلی اتاق نشیمن تمرکز می کنید.<br><i>(نکته: 'Der' نیز در صورت تمرکز بر روی مکان 'اینجا' صحیح است).</i>",
    ku: "Rast e! ☂️ Sîwan: Hûn balê dikişînin ser rewşa giştî ya odeya rûniştinê.<br><i>(Serişte: 'Der' jî rast e heke hûn balê bikişînin ser cîhê 'li vir').</i>",
    ne: "सहि हो! ☂️ छाता: तपाईं बैठक कोठाको सामान्य अवस्थामा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: यदि तपाईं 'यहाँ' स्थानमा ध्यान केन्द्रित गर्नुहुन्छ भने 'Der' पनि सही छ)।</i>",
    ps: "سمه ده! ☂️ چترۍ: تاسو د ناستې خونې عمومي حالت ته پام کوئ.<br><i>(اشاره: 'Der' هم سم دی که تاسو 'دلته' موقعیت ته پام کوئ).</i>",
    pt: "Correto! ☂️ Guarda-chuva: Você foca no estado geral da sala.<br><i>(Dica: 'Der' também está correto se você focar na localização 'aqui dentro').</i>",
    ru: "Правильно! ☂️ Зонт: Вы сосредотачиваетесь на общем состоянии гостиной.<br><i>(Подсказка: «Der» также правильно, если вы сосредотачиваетесь на месте «здесь»).</i>",
    th: "ถูกต้อง! ☂️ ร่ม: คุณเน้นที่สภาพทั่วไปของห้องนั่งเล่น<br><i>(คำแนะนำ: 'Der' ก็ถูกต้องเช่นกัน หากคุณเน้นที่สถานที่ 'ข้างในนี้')</i>",
    tr: "Doğru! ☂️ Şemsiye: Oturma odasının genel durumuna odaklanıyorsunuz.<br><i>(İpucu: 'burası' konumuna odaklanırsanız 'Der' de doğrudur).</i>",
    uk: "Правильно! ☂️ Парасолька: Ви зосереджуєтесь на загальному стані вітальні.<br><i>(Підказка: «Der» також правильне, якщо ви зосереджуєтесь на місці «тут»).</i>",
    ur: "بالکل ٹھیک! ☂️ چھتری: آپ لونگ روم کی عمومی حالت پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Der' بھی صحیح ہے اگر آپ یہاں کے مقام پر توجہ مرکوز کرتے ہیں)۔</i>",
    vi: "Chính xác! ☂️ Ô: Bạn tập trung vào tình trạng chung của phòng khách.<br><i>(Mẹo: 'Der' cũng đúng nếu bạn tập trung vào vị trí 'ở đây').</i>",
    zh: "正确！ ☂️ 雨伞：您关注客厅的一般情况。<br><i>（提示：如果您关注位置“这里”，“Der”也是正确的）。</i>"
  },
  "Rigtigt! 🎯 Pil: Du fokuserer på den specifikke placering 'herinde i stuen'.<br><i>(Tip: 'Det' er også korrekt, hvis du fokuserer på den generelle tilstand).</i>": {
    da: "Rigtigt! 🎯 Pil: Du fokuserer på den specifikke placering 'herinde i stuen'.<br><i>(Tip: 'Det' er også korrekt, hvis du fokuserer på den generelle tilstand).</i>",
    en: "Correct! 🎯 Arrow: You focus on the specific location 'in here in the living room'.<br><i>(Tip: 'Det' is also correct if you focus on the general condition).</i>",
    de: "Richtig! 🎯 Pfeil: Du konzentrierst dich auf den bestimmten Ort 'hier drin im Wohnzimmer'.<br><i>(Tipp: 'Det' ist auch richtig, wenn du dich auf den allgemeinen Zustand konzentrierst).</i>",
    ar: "صحيح! 🎯 السهم: أنت تركز على الموقع المحدد 'هنا في غرفة المعيشة'.<br><i>(نصيحة: 'Det' صحيح أيضًا إذا كنت تركز على الحالة العامة).</i>",
    es: "¡Correcto! 🎯 Flecha: Te enfocas en la ubicación específica 'aquí en la sala'.<br><i>(Consejo: 'Det' también es correcto si te enfocas en la condición general).</i>",
    fa: "درسته! 🎯 فلش: شما روی مکان خاص 'اینجا در اتاق نشیمن' تمرکز می کنید.<br><i>(نکته: 'Det' در صورت تمرکز بر وضعیت کلی نیز صحیح است).</i>",
    ku: "Rast e! 🎯 Tîr: Hûn balê dikişînin ser cihê diyarkirî 'li vir di odeya rûniştinê de'.<br><i>(Serişte: 'Det' jî rast e heke hûn balê bikişînin ser rewşa giştî).</i>",
    ne: "सहि हो! 🎯 तीर: तपाईं 'यहाँ बैठक कोठामा' विशिष्ट स्थानमा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: यदि तपाईं सामान्य अवस्थामा ध्यान केन्द्रित गर्नुहुन्छ भने 'Det' पनि सही छ)।</i>",
    ps: "سمه ده! 🎯 تیر: تاسو ځانګړي ځای ته 'دلته د ناستې خونه کې' پام کوئ.<br><i>(اشاره: 'Det' هم سم دی که تاسو عمومي حالت ته پام کوئ).</i>",
    pt: "Correto! 🎯 Seta: Você foca no local específico 'aqui na sala'.<br><i>(Dica: 'Det' também é correto se você focar na condição geral).</i>",
    ru: "Правильно! 🎯 Стрелка: Вы сосредотачиваетесь на конкретном месте «здесь, в гостиной».<br><i>(Подсказка: «Det» также правильно, если вы сосредотачиваетесь на общем состоянии).</i>",
    th: "ถูกต้อง! 🎯 ลูกศร: คุณเน้นที่สถานที่เฉพาะ 'ข้างในนี้ในห้องนั่งเล่น'<br><i>(คำแนะนำ: 'Det' ก็ถูกต้องเช่นกัน หากคุณเน้นที่สภาพทั่วไป)</i>",
    tr: "Doğru! 🎯 Ok: 'Burada oturma odasındaki' belirli konuma odaklanıyorsunuz.<br><i>(İpucu: Genel duruma odaklanırsanız 'Det' de doğrudur).</i>",
    uk: "Правильно! 🎯 Стрілка: Ви зосереджуєтесь на конкретному місці «тут у вітальні».<br><i>(Підказка: «Det» також правильне, якщо ви зосереджуєтесь на загальному стані).</i>",
    ur: "بالکل ٹھیک! 🎯 تیر: آپ 'یہاں لونگ روم میں' مخصوص مقام پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Det' بھی صحیح ہے اگر آپ عام حالت پر توجہ مرکوز کرتے ہیں)۔</i>",
    vi: "Chính xác! 🎯 Mũi tên: Bạn tập trung vào vị trí cụ thể 'ở đây trong phòng khách'.<br><i>(Mẹo: 'Det' cũng đúng nếu bạn tập trung vào tình trạng chung).</i>",
    zh: "正确！ 🎯 箭头：您关注特定位置“在这里客厅里”。<br><i>（提示：如果您关注一般情况，“Det”也是正确的）。</i>"
  },
  "Rigtigt! 🎯 Pil: Du peger på et helt specifikt, afgrænset punkt (under trappen).": {
    da: "Rigtigt! 🎯 Pil: Du peger på et helt specifikt, afgrænset punkt (under trappen).",
    en: "Correct! 🎯 Arrow: You point to a very specific, defined point (under the stairs).",
    de: "Richtig! 🎯 Pfeil: Du weist auf einen ganz bestimmten, definierten Punkt hin (unter der Treppe).",
    ar: "صحيح! 🎯 السهم: أنت تشير إلى نقطة محددة ومحددة للغاية (تحت الدرج).",
    es: "¡Correcto! 🎯 Flecha: Señalas un punto muy específico y definido (debajo de las escaleras).",
    fa: "درسته! 🎯 فلش: شما به یک نقطه کاملاً مشخص و تعریف شده (زیر پله ها) اشاره می کنید.",
    ku: "Rast e! 🎯 Tîr: Hûn xalek pir diyarkirî, diyarkirî (di binê derenceyan de) nîşan didin.",
    ne: "सहि हो! 🎯 तीर: तपाईं एक धेरै विशिष्ट, परिभाषित बिन्दु (सिँढी मुनि) औंल्याउनुहुन्छ।",
    ps: "سمه ده! 🎯 تیر: تاسو خورا ځانګړي ، تعریف شوي ټکي (د زینو لاندې) ته اشاره کوئ.",
    pt: "Correto! 🎯 Seta: Você aponta para um ponto muito específico e definido (debaixo das escadas).",
    ru: "Правильно! 🎯 Стрелка: Вы указываете на очень конкретную, определенную точку (под лестницей).",
    th: "ถูกต้อง! 🎯 ลูกศร: คุณชี้ไปที่จุดที่เฉพาะเจาะจงมาก (ใต้บันได)",
    tr: "Doğru! 🎯 Ok: Çok belirgin, tanımlanmış bir noktaya (merdivenlerin altı) işaret ediyorsunuz.",
    uk: "Правильно! 🎯 Стрілка: Ми вказуємо на дуже конкретну, визначену точку (під сходами).",
    ur: "بالکل ٹھیک! 🎯 تیر: آپ ایک بہت ہی مخصوص، متعین نقطہ (سیڑھیوں کے نیچے) کی طرف اشارہ کرتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Bạn chỉ vào một điểm rất cụ thể, được xác định (dưới cầu thang).",
    zh: "正确！ 🎯 箭头：您指向一个非常具体、定义的点（楼梯下）。"
  },
  "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle tilstand (at der er mørkt).<br><i>('Der' er ofte mere naturligt her, da vi fokuserer stærkt på det specifikke sted).</i>": {
    da: "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle tilstand (at der er mørkt).<br><i>('Der' er ofte mere naturligt her, da vi fokuserer stærkt på det specifikke sted).</i>",
    en: "Correct! ☂️ Umbrella: You focus on the general condition (that it is dark).<br><i>('Der' is often more natural here, as we focus strongly on the specific place).</i>",
    de: "Richtig! ☂️ Regenschirm: Du konzentrierst dich auf den allgemeinen Zustand (dass es dunkel ist).<br><i>('Der' ist hier oft natürlicher, da wir uns stark auf den spezifischen Ort konzentrieren).</i>",
    ar: "صحيح! ☂️ مظلة: أنت تركز على الحالة العامة (أنها مظلمة).<br><i>('Der' غالبًا ما يكون أكثر طبيعية هنا، حيث نركز بشدة على المكان المحدد).</i>",
    es: "¡Correcto! ☂️ Paraguas: Te enfocas en la condición general (que está oscuro).<br><i>('Der' a menudo es más natural aquí, ya que nos enfocamos fuertemente en el lugar específico).</i>",
    fa: "درسته! ☂️ چتر: شما روی وضعیت کلی (تاریک بودن آن) تمرکز می کنید.<br><i>('Der' اغلب در اینجا طبیعی تر است، زیرا ما به شدت روی مکان خاص تمرکز می کنیم).</i>",
    ku: "Rast e! ☂️ Sîwan: Hûn balê dikişînin ser rewşa giştî (ku tarî ye).<br><i>('Der' bi gelemperî li vir xwezayîtir e, ji ber ku em bi xurtî li ser cîhê diyarkirî hûr dibin).</i>",
    ne: "सहि हो! ☂️ छाता: तपाईं सामान्य अवस्थामा ध्यान केन्द्रित गर्नुहुन्छ (कि यो अँध्यारो छ)।<br><i>('Der' प्रायः यहाँ अधिक प्राकृतिक छ, किनकि हामी विशिष्ट ठाउँमा दृढतापूर्वक ध्यान केन्द्रित गर्दछौं)।</i>",
    ps: "سمه ده! ☂️ چترۍ: تاسو په عمومي حالت تمرکز کوئ (چې تیاره ده).<br><i>('Der' دلته اکثرا ډیر طبیعي وي ، ځکه چې موږ په ځانګړي ځای باندې قوي تمرکز کوو).</i>",
    pt: "Correto! ☂️ Guarda-chuva: Você foca no estado geral (que está escuro).<br><i>('Der' é frequentemente mais natural aqui, pois focamos fortemente no lugar específico).</i>",
    ru: "Правильно! ☂️ Зонт: Вы сосредотачиваетесь на общем состоянии (что здесь темно).<br><i>(«Der» здесь часто более естественно, так как мы сильно фокусируемся на конкретном месте).</i>",
    th: "ถูกต้อง! ☂️ ร่ม: คุณเน้นที่สภาพทั่วไป (ว่ามืด)<br><i>('Der' มักจะฟังดูเป็นธรรมชาติกว่าที่นี่ เนื่องจากเราเน้นที่สถานที่เฉพาะ)</i>",
    tr: "Doğru! ☂️ Şemsiye: Genel duruma (karanlık olduğuna) odaklanıyorsunuz.<br><i>(Burada, belirli bir yere güçlü bir şekilde odaklandığımız için 'Der' genellikle daha doğaldır).</i>",
    uk: "Правильно! ☂️ Парасолька: Ви зосереджуєтесь на загальному стані (що там темно).<br><i>(«Der» тут часто більш природно, оскільки ми сильно фокусуємося на конкретному місці).</i>",
    ur: "بالکل ٹھیک! ☂️ چھتری: آپ عام حالت پر توجہ مرکوز کرتے ہیں (کہ یہ اندھیرا ہے)۔<br><i>('Der' اکثر یہاں زیادہ قدرتی ہوتا ہے، کیونکہ ہم مخصوص جگہ پر زیادہ توجہ دیتے ہیں)۔</i>",
    vi: "Chính xác! ☂️ Ô: Bạn tập trung vào tình trạng chung (rằng trời tối).<br><i>('Der' thường tự nhiên hơn ở đây, vì chúng tôi tập trung mạnh vào địa điểm cụ thể).</i>",
    zh: "正确！ ☂️ 雨伞：您关注一般情况（很黑）。<br><i>（“Der”在这里通常更自然，因为我们非常关注特定地点）。</i>"
  },
  "Rigtigt! ☂️ Paraply: Varmen beskriver vejret generelt.<br><i>(Tip: 'Der' er også korrekt, da vi taler om placeringen 'i Danmark').</i>": {
    da: "Rigtigt! ☂️ Paraply: Varmen beskriver vejret generelt.<br><i>(Tip: 'Der' er også korrekt, da vi taler om placeringen 'i Danmark').</i>",
    en: "Correct! ☂️ Umbrella: The heat describes the weather in general.<br><i>(Tip: 'Der' is also correct, as we talk about the location 'in Denmark').</i>",
    de: "Richtig! ☂️ Regenschirm: Die Hitze beschreibt das Wetter im Allgemeinen.<br><i>(Tipp: 'Der' ist auch richtig, da wir über den Ort 'in Dänemark' sprechen).</i>",
    ar: "صحيح! ☂️ مظلة: الحرارة تصف الطقس بشكل عام.<br><i>(نصيحة: 'Der' صحيح أيضًا ، حيث نتحدث عن الموقع 'في الدنمارك').</i>",
    es: "¡Correcto! ☂️ Paraguas: El calor describe el clima en general.<br><i>(Consejo: 'Der' también es correcto, ya que hablamos de la ubicación 'en Dinamarca').</i>",
    fa: "درسته! ☂️ چتر: گرما آب و هوا را به طور کلی توصیف می کند.<br><i>(نکته: 'Der' نیز صحیح است، زیرا در مورد مکان 'در دانمارک' صحبت می کنیم).</i>",
    ku: "Rast e! ☂️ Sîwan: Germahiya hewayê bi giştî vedibêje.<br><i>(Serişte: 'Der' jî rast e, ji ber ku em qala cîhê 'li Danîmarkayê' dikin).</i>",
    ne: "सहि हो! ☂️ छाता: गर्मीले सामान्यतया मौसमलाई वर्णन गर्दछ।<br><i>(सुझाव: 'Der' पनि सही छ, किनकि हामी 'डेनमार्कमा' स्थानको बारेमा कुरा गर्छौं)।</i>",
    ps: "سمه ده! ☂️ چترۍ: تودوخه په عمومي ډول هوا بیانوي.<br><i>(اشاره: 'Der' هم سم دی ، ځکه چې موږ د 'ډنمارک کې' موقعیت په اړه خبرې کوو).</i>",
    pt: "Correto! ☂️ Guarda-chuva: O calor descreve o clima em geral.<br><i>(Dica: 'Der' também é correto, pois falamos sobre a localização 'na Dinamarca').</i>",
    ru: "Правильно! ☂️ Зонт: Жара описывает погоду в целом.<br><i>(Подсказка: «Der» также правильно, так как мы говорим о месте «в Дании»).</i>",
    th: "ถูกต้อง! ☂️ ร่ม: ความร้อนอธิบายสภาพอากาศโดยทั่วไป<br><i>(คำแนะนำ: 'Der' ก็ถูกต้องเช่นกัน เนื่องจากเราพูดถึงสถานที่ 'ในเดนมาร์ก')</i>",
    tr: "Doğru! ☂️ Şemsiye: Sıcaklık genel olarak hava durumunu tanımlar.<br><i>(İpucu: 'Danimarka'daki' konumdan bahsettiğimiz için 'Der' de doğrudur).</i>",
    uk: "Правильно! ☂️ Парасолька: Спека описує погоду в цілому.<br><i>(Підказка: «Der» також правильне, оскільки ми говоримо про місце «в Данії»).</i>",
    ur: "بالکل ٹھیک! ☂️ چھتری: گرمی عام طور پر موسم کو بیان کرتی ہے۔<br><i>(ٹپ: 'Der' بھی صحیح ہے، کیونکہ ہم 'ڈنمارک میں' کے مقام کے بارے میں بات کرتے ہیں)۔</i>",
    vi: "Chính xác! ☂️ Ô: Cái nóng mô tả thời tiết nói chung.<br><i>(Mẹo: 'Der' cũng đúng, vì chúng ta nói về vị trí 'ở Đan Mạch').</i>",
    zh: "正确！ ☂️ 雨伞：炎热描述了一般的天气。<br><i>（提示：“Der”也是正确的，因为我们谈论的是“在丹麦”这个位置）。</i>"
  },
  "Rigtigt! 🎯 Pil: Du fokuserer på placeringen (Danmark).<br><i>(Tip: 'Det' er også meget almindeligt for at beskrive det generelle vejr).</i>": {
    da: "Rigtigt! 🎯 Pil: Du fokuserer på placeringen (Danmark).<br><i>(Tip: 'Det' er også meget almindeligt for at beskrive det generelle vejr).</i>",
    en: "Correct! 🎯 Arrow: You focus on the location (Denmark).<br><i>(Tip: 'Det' is also very common to describe the general weather).</i>",
    de: "Richtig! 🎯 Pfeil: Du konzentrierst dich auf den Ort (Dänemark).<br><i>(Tipp: 'Det' ist auch sehr üblich, um das allgemeine Wetter zu beschreiben).</i>",
    ar: "صحيح! 🎯 السهم: أنت تركز على الموقع (الدنمارك).<br><i>(نصيحة: 'Det' شائع جدًا أيضًا لوصف الطقس العام).</i>",
    es: "¡Correcto! 🎯 Flecha: Te enfocas en la ubicación (Dinamarca).<br><i>(Consejo: 'Det' también es muy común para describir el clima general).</i>",
    fa: "درسته! 🎯 فلش: شما روی مکان (دانمارک) تمرکز می کنید.<br><i>(نکته: 'Det' نیز برای توصیف آب و هوای کلی بسیار رایج است).</i>",
    ku: "Rast e! 🎯 Tîr: Hûn balê dikişînin ser cihê (Danimarka).<br><i>(Serişte: 'Det' ji bo danasîna hewaya giştî jî pir gelemperî ye).</i>",
    ne: "सहि हो! 🎯 तीर: तपाईं स्थान (डेनमार्क) मा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: 'Det' सामान्य मौसम वर्णन गर्न पनि धेरै सामान्य छ)।</i>",
    ps: "سمه ده! 🎯 تیر: تاسو موقعیت (ډنمارک) ته پام کوئ.<br><i>(اشاره: 'Det' د عمومي هوا بیانولو لپاره هم خورا عام دی).</i>",
    pt: "Correto! 🎯 Seta: Você foca na localização (Dinamarca).<br><i>(Dica: 'Det' também é muito comum para descrever o clima geral).</i>",
    ru: "Правильно! 🎯 Стрелка: Вы сосредотачиваетесь на местоположении (Дания).<br><i>(Подсказка: «Det» также очень часто используется для описания общей погоды).</i>",
    th: "ถูกต้อง! 🎯 ลูกศร: คุณเน้นที่สถานที่ (เดนมาร์ก)<br><i>(คำแนะนำ: 'Det' มักใช้เพื่ออธิบายสภาพอากาศโดยทั่วไปเช่นกัน)</i>",
    tr: "Doğru! 🎯 Ok: Konuma (Danimarka) odaklanıyorsunuz.<br><i>(İpucu: Genel hava durumunu tanımlamak için 'Det' de çok yaygındır).</i>",
    uk: "Правильно! 🎯 Стрілка: Ви зосереджуєтесь на місці (Данія).<br><i>(Підказка: «Det» також дуже часто використовується для опису загальної погоди).</i>",
    ur: "بالکل ٹھیک! 🎯 تیر: آپ مقام (ڈنمارک) پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Det' بھی عام موسم کو بیان کرنے کے لیے بہت عام ہے)۔</i>",
    vi: "Chính xác! 🎯 Mũi tên: Bạn tập trung vào địa điểm (Đan Mạch).<br><i>(Mẹo: 'Det' cũng rất phổ biến để mô tả thời tiết chung).</i>",
    zh: "正确！ 🎯 箭头：您关注位置（丹麦）。<br><i>（提示：“Det”在描述一般天气时也很常见）。</i>"
  },
  "Tænk på Pilen. Vi zoomer ind på en bestemt placering (i koppen) og den fysiske kaffe.": {
    da: "Tænk på Pilen. Vi zoomer ind på en bestemt placering (i koppen) og den fysiske kaffe.",
    en: "Think of the Arrow. We zoom in on a specific location (in the cup) and the physical coffee.",
    de: "Denke an den Pfeil. Wir zoomen auf einen bestimmten Ort (in der Tasse) und den physischen Kaffee.",
    ar: "فكر في السهم. نقوم بالتكبير على موقع معين (في الكوب) والقهوة المادية.",
    es: "Piensa en la Flecha. Hacemos zoom en una ubicación específica (en la taza) y el café físico.",
    fa: "به فلش فکر کنید. ما روی یک مکان خاص (در فنجان) و قهوه فیزیکی زوم می کنیم.",
    ku: "Tîrê bifikirin. Em li cîhek diyarkirî (di qedehê de) û qehweya laşî nêzîk dibin.",
    ne: "तीरको बारेमा सोच्नुहोस्। हामी एक विशेष स्थान (कपमा) र भौतिक कफीमा जुम इन गर्छौं।",
    ps: "د تیر په اړه فکر وکړئ. موږ په یوه ځانګړي ځای (کپ کې) او فزیکي قهوه کې زوم کوو.",
    pt: "Pense na Seta. Damos um zoom em um local específico (na xícara) e no café físico.",
    ru: "Подумайте о Стрелке. Мы приближаем определенное место (в чашке) и физический кофе.",
    th: "นึกถึงลูกศร เราซูมเข้าไปที่ตำแหน่งเฉพาะ (ในถ้วย) และกาแฟที่จับต้องได้",
    tr: "Oku düşünün. Belirli bir konuma (fincanın içine) ve fiziksel kahveye odaklanıyoruz.",
    uk: "Подумайте про Стрілку. Ми збільшуємо певне місце (у чашці) та фізичну каву.",
    ur: "تیر کے بارے میں سوچیں۔ ہم ایک مخصوص مقام (کپ میں) اور جسمانی کافی پر زوم ان کرتے ہیں۔",
    vi: "Hãy nghĩ về Mũi tên. Chúng tôi phóng to một vị trí cụ thể (trong cốc) và cà phê vật lý.",
    zh: "想想箭头。我们放大了特定位置（杯子里）和实物咖啡。"
  },
  "Rigtigt! 🎯 Pil: Vi zoomer ind på en bestemt placering (i koppen) og peger på kaffen dér. Her kan man KUN bruge 'der'.": {
    da: "Rigtigt! 🎯 Pil: Vi zoomer ind på en bestemt placering (i koppen) og peger på kaffen dér. Her kan man KUN bruge 'der'.",
    en: "Correct! 🎯 Arrow: We zoom in on a specific location (in the cup) and point to the coffee there. Here you can ONLY use 'der'.",
    de: "Richtig! 🎯 Pfeil: Wir zoomen auf einen bestimmten Ort (in der Tasse) und zeigen auf den Kaffee dort. Hier kann man NUR 'der' verwenden.",
    ar: "صحيح! 🎯 السهم: نقوم بالتكبير على موقع معين (في الكوب) ونشير إلى القهوة هناك. هنا يمكنك استخدام 'der' فقط.",
    es: "¡Correcto! 🎯 Flecha: Hacemos zoom en una ubicación específica (en la taza) y señalamos el café allí. Aquí SOLO puedes usar 'der'.",
    fa: "درسته! 🎯 فلش: روی مکان خاصی (در فنجان) زوم می کنیم و به قهوه آنجا اشاره می کنیم. در اینجا شما فقط می توانید از 'der' استفاده کنید.",
    ku: "Rast e! 🎯 Tîr: Em li cîhek diyarkirî (di qedehê de) nêzîk dibin û qehweya li wir destnîşan dikin. Li vir hûn dikarin TENÊ 'der' bikar bînin.",
    ne: "सहि हो! 🎯 तीर: हामी एक विशेष स्थान (कपमा) जुम इन गर्छौं र त्यहाँ कफीलाई संकेत गर्छौं। यहाँ तपाईं मात्र 'der' प्रयोग गर्न सक्नुहुन्छ।",
    ps: "سمه ده! 🎯 تیر: موږ په یو ځانګړي ځای کې (په پیاله کې) زوم کوو او هلته قهوه ته اشاره کوو. دلته تاسو یوازې کارولی شئ 'der'.",
    pt: "Correto! 🎯 Seta: Damos um zoom em um local específico (na xícara) e apontamos para o café ali. Aqui você SÓ pode usar 'der'.",
    ru: "Правильно! 🎯 Стрелка: Мы приближаем определенное место (в чашке) и указываем на кофе там. Здесь можно использовать ТОЛЬКО «der».",
    th: "ถูกต้อง! 🎯 ลูกศร: เราซูมเข้าไปที่ตำแหน่งเฉพาะ (ในถ้วย) และชี้ไปที่กาแฟตรงนั้น ที่นี่คุณใช้ได้แค่ 'der' เท่านั้น",
    tr: "Doğru! 🎯 Ok: Belirli bir konuma (fincanın içine) odaklanıyoruz ve oradaki kahveyi işaret ediyoruz. Burada SADECE 'der' kullanabilirsiniz.",
    uk: "Правильно! 🎯 Стрілка: Ми збільшуємо певне місце (у чашці) і вказуємо на каву там. Тут можна використовувати ТІЛЬКИ «der».",
    ur: "بالکل ٹھیک! 🎯 تیر: ہم ایک مخصوص مقام (کپ میں) پر زوم ان کرتے ہیں اور وہاں کافی کی طرف اشارہ کرتے ہیں۔ یہاں آپ صرف 'der' استعمال کر سکتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Chúng tôi phóng to một vị trí cụ thể (trong cốc) và chỉ vào cà phê ở đó. Ở đây bạn CHỈ có thể sử dụng 'der'.",
    zh: "正确！ 🎯 箭头：我们放大特定位置（杯子里）并指向那里的咖啡。这里你只能使用“der”。"
  },
  "Tænk på Pilen. Vi henleder opmærksomheden på et barn på en specifik placering (inde i soveværelset).": {
    da: "Tænk på Pilen. Vi henleder opmærksomheden på et barn på en specifik placering (inde i soveværelset).",
    en: "Think of the Arrow. We draw attention to a child in a specific location (inside the bedroom).",
    de: "Denke an den Pfeil. Wir lenken die Aufmerksamkeit auf ein Kind an einem bestimmten Ort (im Schlafzimmer).",
    ar: "فكر في السهم. نلفت الانتباه إلى طفل في مكان محدد (داخل غرفة النوم).",
    es: "Piensa en la Flecha. Llamamos la atención sobre un niño en una ubicación específica (dentro del dormitorio).",
    fa: "به فلش فکر کنید. ما توجه را به کودکی در یک مکان خاص (در داخل اتاق خواب) جلب می کنیم.",
    ku: "Tîrê bifikirin. Em balê dikişînin ser zarokek li cîhek diyarkirî (di hundurê jûreya razanê de).",
    ne: "तीरको बारेमा सोच्नुहोस्। हामी एक विशेष स्थान (सुत्ने कोठा भित्र) मा एक बच्चालाई ध्यान आकर्षित गर्छौं।",
    ps: "د تیر په اړه فکر وکړئ. موږ په یو ځانګړي ځای کې (د خوب خونه دننه) یوه ماشوم ته پام راجلبوو.",
    pt: "Pense na Seta. Chamamos a atenção para uma criança em um local específico (dentro do quarto).",
    ru: "Подумайте о Стрелке. Мы обращаем внимание на ребенка в определенном месте (в спальне).",
    th: "นึกถึงลูกศร เราดึงความสนใจไปที่เด็กในสถานที่เฉพาะ (ในห้องนอน)",
    tr: "Oku düşünün. Belirli bir yerdeki (yatak odasının içindeki) bir çocuğa dikkat çekiyoruz.",
    uk: "Подумайте про Стрілку. Ми звертаємо увагу на дитину в певному місці (всередині спальні).",
    ur: "تیر کے بارے میں سوچیں۔ ہم ایک مخصوص مقام (بیڈروم کے اندر) پر ایک بچے کی طرف توجہ مبذول کرتے ہیں۔",
    vi: "Hãy nghĩ về Mũi tên. Chúng tôi thu hút sự chú ý đến một đứa trẻ ở một vị trí cụ thể (bên trong phòng ngủ).",
    zh: "想想箭头。我们提请注意特定位置（卧室里）的孩子。"
  },
  "Rigtigt! 🎯 Pil: Vi peger på en specifik placering, hvor et barn befinder sig. Her kan man KUN sige 'der'.": {
    da: "Rigtigt! 🎯 Pil: Vi peger på en specifik placering, hvor et barn befinder sig. Her kan man KUN sige 'der'.",
    en: "Correct! 🎯 Arrow: We point to a specific location where a child is. Here you can ONLY say 'der'.",
    de: "Richtig! 🎯 Pfeil: Wir weisen auf einen bestimmten Ort hin, an dem sich ein Kind befindet. Hier kann man NUR 'der' sagen.",
    ar: "صحيح! 🎯 السهم: نحن نشير إلى موقع محدد يتواجد فيه طفل. هنا يمكنك فقط أن تقول 'der'.",
    es: "¡Correcto! 🎯 Flecha: Señalamos una ubicación específica donde hay un niño. Aquí SOLO puedes decir 'der'.",
    fa: "درسته! 🎯 فلش: ما به مکان خاصی اشاره می کنیم که کودک در آن قرار دارد. در اینجا شما فقط می توانید 'der' بگویید.",
    ku: "Rast e! 🎯 Tîr: Em cihê diyarkirî yê ku zarok lê ye destnîşan dikin. Li vir hûn dikarin TENÊ bibêjin 'der'.",
    ne: "सहि हो! 🎯 तीर: हामी एक निश्चित स्थान औंल्याउँछौं जहाँ बच्चा छ। यहाँ तपाईं केवल 'der' भन्न सक्नुहुन्छ।",
    ps: "سمه ده! 🎯 تیر: موږ یو ځانګړي ځای ته اشاره کوو چیرې چې ماشوم وي. دلته تاسو یوازې ویلای شئ 'der'.",
    pt: "Correto! 🎯 Seta: Apontamos para um local específico onde há uma criança. Aqui você SÓ pode dizer 'der'.",
    ru: "Правильно! 🎯 Стрелка: Мы указываем на конкретное место, где находится ребенок. Здесь можно сказать ТОЛЬКО «der».",
    th: "ถูกต้อง! 🎯 ลูกศร: เราชี้ไปที่สถานที่เฉพาะที่มีเด็กอยู่ ที่นี่คุณพูดได้แค่ 'der' เท่านั้น",
    tr: "Doğru! 🎯 Ok: Bir çocuğun bulunduğu belirli bir yere işaret ediyoruz. Burada SADECE 'der' diyebilirsiniz.",
    uk: "Правильно! 🎯 Стрілка: Ми вказуємо на конкретне місце, де знаходиться дитина. Тут можна сказати ТІЛЬКИ «der».",
    ur: "بالکل ٹھیک! 🎯 تیر: ہم ایک مخصوص مقام کی طرف اشارہ کرتے ہیں جہاں ایک بچہ ہے۔ یہاں آپ صرف 'der' کہہ سکتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Chúng tôi chỉ vào một vị trí cụ thể nơi có một đứa trẻ. Ở đây bạn CHỈ có thể nói 'der'.",
    zh: "正确！ 🎯 箭头：我们指向孩子所在的特定位置。这里你只能说“der”。"
  },
  "Tænk på Paraplyen. Vi taler om vejret og den generelle tilstand.": {
    da: "Tænk på Paraplyen. Vi taler om vejret og den generelle tilstand.",
    en: "Think of the Umbrella. We talk about the weather and the general condition.",
    de: "Denke an den Regenschirm. Wir sprechen über das Wetter und den allgemeinen Zustand.",
    ar: "فكر في المظلة. نحن نتحدث عن الطقس والحالة العامة.",
    es: "Piensa en el Paraguas. Hablamos del clima y la condición general.",
    fa: "به چتر فکر کنید. ما در مورد آب و هوا و وضعیت عمومی صحبت می کنیم.",
    ku: "Sîwanê bifikirin. Em behsa hewa û rewşa giştî dikin.",
    ne: "छाताको बारेमा सोच्नुहोस्। हामी मौसम र सामान्य अवस्थाको बारेमा कुरा गर्छौं।",
    ps: "د چترۍ په اړه فکر وکړئ. موږ د هوا او عمومي وضعیت په اړه خبرې کوو.",
    pt: "Pense no Guarda-chuva. Falamos sobre o clima e a condição geral.",
    ru: "Подумайте о Зонте. Мы говорим о погоде и общем состоянии.",
    th: "นึกถึงร่ม เราพูดถึงสภาพอากาศและสภาพทั่วไป",
    tr: "Şemsiyeyi düşünün. Hava durumu ve genel durum hakkında konuşuyoruz.",
    uk: "Подумайте про Парасольку. Ми говоримо про погоду та загальний стан.",
    ur: "چھتری کے بارے میں سوچیں۔ ہم موسم اور عمومی حالت کے بارے میں بات کرتے ہیں۔",
    vi: "Hãy nghĩ về cái Ô. Chúng ta nói về thời tiết và điều kiện chung.",
    zh: "想想雨伞。我们谈论天气和一般情况。"
  },
  "Rigtigt! ☂️ Paraply: Varmen og solen beskriver vejret og den generelle tilstand. Her bruger vi 'det'.": {
    da: "Rigtigt! ☂️ Paraply: Varmen og solen beskriver vejret og den generelle tilstand. Her bruger vi 'det'.",
    en: "Correct! ☂️ Umbrella: The heat and sun describe the weather and the general condition. Here we use 'det'.",
    de: "Richtig! ☂️ Regenschirm: Die Hitze und die Sonne beschreiben das Wetter und den allgemeinen Zustand. Hier verwenden wir 'det'.",
    ar: "صحيح! ☂️ مظلة: تصف الحرارة والشمس الطقس والحالة العامة. هنا نستخدم 'det'.",
    es: "¡Correcto! ☂️ Paraguas: El calor y el sol describen el clima y la condición general. Aquí usamos 'det'.",
    fa: "درسته! ☂️ چتر: گرما و خورشید آب و هوا و وضعیت عمومی را توصیف می کنند. در اینجا ما از 'det' استفاده می کنیم.",
    ku: "Rast e! ☂️ Sîwan: Germa û tav hewa û rewşa giştî vedibêje. Li vir em 'det' bikar tînin.",
    ne: "सहि हो! ☂️ छाता: गर्मी र घामले मौसम र सामान्य अवस्थालाई वर्णन गर्दछ। यहाँ हामी 'det' प्रयोग गर्छौं।",
    ps: "سمه ده! ☂️ چترۍ: تودوخه او لمر د هوا او عمومي وضعیت تشریح کوي. دلته موږ 'det' کاروو.",
    pt: "Correto! ☂️ Guarda-chuva: O calor e o sol descrevem o clima e a condição geral. Aqui usamos 'det'.",
    ru: "Правильно! ☂️ Зонт: Жара и солнце описывают погоду и общее состояние. Здесь мы используем «det».",
    th: "ถูกต้อง! ☂️ ร่ม: ความร้อนและแสงแดดอธิบายสภาพอากาศและสภาพทั่วไป ที่นี่เราใช้ 'det'",
    tr: "Doğru! ☂️ Şemsiye: Sıcaklık ve güneş, hava durumunu ve genel durumu tanımlar. Burada 'det' kullanıyoruz.",
    uk: "Правильно! ☂️ Парасолька: Спека та сонце описують погоду та загальний стан. Тут ми використовуємо «det».",
    ur: "بالکل ٹھیک! ☂️ چھتری: گرمی اور سورج موسم اور عمومی حالت کو بیان کرتے ہیں۔ یہاں ہم 'det' استعمال کرتے ہیں۔",
    vi: "Chính xác! ☂️ Ô: Nắng và nóng mô tả thời tiết và tình trạng chung. Ở đây chúng ta sử dụng 'det'.",
    zh: "正确！ ☂️ 雨伞：炎热和阳光描述了天气和一般情况。这里我们使用“det”。"
  },
  "Tænk på Pilen. Vi peger på en bestemt fysisk ting (taxaen) på en specifik placering (ude foran).": {
    da: "Tænk på Pilen. Vi peger på en bestemt fysisk ting (taxaen) på en specifik placering (ude foran).",
    en: "Think of the Arrow. We point to a specific physical thing (the taxi) in a specific location (out front).",
    de: "Denke an den Pfeil. Wir weisen auf eine bestimmte physische Sache (das Taxi) an einem bestimmten Ort (draußen vor) hin.",
    ar: "فكر في السهم. نحن نشير إلى شيء مادي محدد (سيارة الأجرة) في مكان معين (في الخارج).",
    es: "Piensa en la Flecha. Señalamos una cosa física específica (el taxi) en una ubicación específica (afuera).",
    fa: "به فلش فکر کنید. ما به یک چیز فیزیکی خاص (تاکسی) در یک مکان خاص (بیرون) اشاره می کنیم.",
    ku: "Tîrê bifikirin. Em tiştek laşî yê diyarkirî (taksî) li cîhek taybetî (li derve) nîşan didin.",
    ne: "तीरको बारेमा सोच्नुहोस्। हामी एक विशेष स्थान (बाहिर) मा एक विशेष भौतिक कुरा (ट्याक्सी) औंल्याउँछौं।",
    ps: "د تیر په اړه فکر وکړئ. موږ په ځانګړي موقعیت کې (بهر) یو ځانګړي فزیکي شی (ټکسي) ته اشاره کوو.",
    pt: "Pense na Seta. Apontamos para uma coisa física específica (o táxi) em um local específico (lá fora).",
    ru: "Подумайте о Стрелке. Мы указываем на конкретную физическую вещь (такси) в определенном месте (снаружи).",
    th: "นึกถึงลูกศร เราชี้ไปที่สิ่งของทางกายภาพเฉพาะ (แท็กซี่) ในตำแหน่งเฉพาะ (ข้างหน้า)",
    tr: "Oku düşünün. Belirli bir konumdaki (dışarıdaki) belirli bir fiziksel nesneyi (taksiyi) işaret ediyoruz.",
    uk: "Подумайте про Стрілку. Ми вказуємо на конкретну фізичну річ (таксі) у певному місці (на вулиці).",
    ur: "تیر کے بارے میں سوچیں۔ ہم ایک مخصوص مقام (باہر) پر ایک مخصوص جسمانی چیز (ٹیکسی) کی طرف اشارہ کرتے ہیں۔",
    vi: "Hãy nghĩ về Mũi tên. Chúng tôi chỉ vào một vật thể vật lý cụ thể (taxi) ở một vị trí cụ thể (phía trước).",
    zh: "想想箭头。我们指向特定位置（前面）的特定物理事物（出租车）。"
  },
  "Rigtigt! 🎯 Pil: Vi peger på en specifik taxa, som befinder sig på en specifik placering ude foran. Man kan KUN bruge 'der'.": {
    da: "Rigtigt! 🎯 Pil: Vi peger på en specifik taxa, som befinder sig på en specifik placering ude foran. Man kan KUN bruge 'der'.",
    en: "Correct! 🎯 Arrow: We point to a specific taxi located in a specific location out front. You can ONLY use 'der'.",
    de: "Richtig! 🎯 Pfeil: Wir weisen auf ein bestimmtes Taxi hin, das sich an einem bestimmten Ort draußen befindet. Man kann NUR 'der' verwenden.",
    ar: "صحيح! 🎯 السهم: نحن نشير إلى سيارة أجرة محددة تقع في موقع محدد بالخارج. يمكنك استخدام 'der' فقط.",
    es: "¡Correcto! 🎯 Flecha: Señalamos un taxi específico ubicado en una ubicación específica afuera. SOLO puedes usar 'der'.",
    fa: "درسته! 🎯 فلش: ما به یک تاکسی خاص که در یک مکان خاص در خارج قرار دارد اشاره می کنیم. شما فقط می توانید از 'der' استفاده کنید.",
    ku: "Rast e! 🎯 Tîr: Em texsiyek diyarkirî ya li cîhek diyarkirî ya derve nîşan didin. Hûn dikarin TENÊ 'der' bikar bînin.",
    ne: "सहि हो! 🎯 तीर: हामी बाहिर एक निश्चित स्थानमा अवस्थित एक विशेष ट्याक्सीलाई संकेत गर्छौं। तपाईं मात्र 'der' प्रयोग गर्न सक्नुहुन्छ।",
    ps: "سمه ده! 🎯 تیر: موږ یوه ځانګړې ټکسي ته اشاره کوو چې بهر په یو ځانګړي موقعیت کې موقعیت لري. تاسو یوازې کارولی شئ 'der'.",
    pt: "Correto! 🎯 Seta: Apontamos para um táxi específico localizado em um local específico lá fora. Você SÓ pode usar 'der'.",
    ru: "Правильно! 🎯 Стрелка: Мы указываем на конкретное такси, расположенное в определенном месте снаружи. Вы можете использовать ТОЛЬКО «der».",
    th: "ถูกต้อง! 🎯 ลูกศร: เราชี้ไปที่รถแท็กซี่เฉพาะที่อยู่ในตำแหน่งเฉพาะข้างนอก คุณใช้ได้แค่ 'der' เท่านั้น",
    tr: "Doğru! 🎯 Ok: Dışarıdaki belirli bir konumda bulunan belirli bir taksiyi işaret ediyoruz. SADECE 'der' kullanabilirsiniz.",
    uk: "Правильно! 🎯 Стрілка: Ми вказуємо на конкретне таксі, що знаходиться в певному місці на вулиці. Ви можете використовувати ТІЛЬКИ «der».",
    ur: "بالکل ٹھیک! 🎯 تیر: ہم ایک مخصوص ٹیکسی کی طرف اشارہ کرتے ہیں جو باہر ایک مخصوص مقام پر واقع ہے۔ آپ صرف 'der' استعمال کر سکتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Chúng tôi chỉ vào một chiếc taxi cụ thể nằm ở một vị trí cụ thể ở phía trước. Bạn CHỈ có thể sử dụng 'der'.",
    zh: "正确！ 🎯 箭头：我们指向位于前面特定位置的特定出租车。你只能使用“der”。"
  },
  "Tænk på Paraplyen. At 'det trækker' beskriver en usynlig tilstand i rummet, lidt ligesom vejret.": {
    da: "Tænk på Paraplyen. At 'det trækker' beskriver en usynlig tilstand i rummet, lidt ligesom vejret.",
    en: "Think of the Umbrella. That 'it is drafty' describes an invisible condition in the room, somewhat like the weather.",
    de: "Denke an den Regenschirm. Dass 'es zieht' beschreibt einen unsichtbaren Zustand im Raum, ähnlich wie das Wetter.",
    ar: "فكر في المظلة. حقيقة 'أنه عاصف' يصف حالة غير مرئية في الغرفة، تشبه إلى حد ما الطقس.",
    es: "Piensa en el Paraguas. Que 'hay corriente' describe una condición invisible en la habitación, algo así como el clima.",
    fa: "به چتر فکر کنید. اینکه 'باد می آید' یک وضعیت نامرئی در اتاق را توصیف می کند، چیزی شبیه به آب و هوا.",
    ku: "Sîwanê bifikirin. Ku 'bayê sar e' rewşek nedîtî li odeyê vedibêje, mîna hewayê.",
    ne: "छाताको बारेमा सोच्नुहोस्। त्यो 'ड्राफ्टी छ' ले कोठामा अदृश्य अवस्थाको वर्णन गर्दछ, मौसम जस्तै।",
    ps: "د چترۍ په اړه فکر وکړئ. هغه 'دا مسوده ده' په خونه کې یو ناڅرګند حالت بیانوي، یو څه د هوا په څیر.",
    pt: "Pense no Guarda-chuva. O fato de 'estar com corrente de ar' descreve uma condição invisível no ambiente, parecido com o clima.",
    ru: "Подумайте о Зонте. То, что «сквозит», описывает невидимое состояние в комнате, чем-то похожее на погоду.",
    th: "นึกถึงร่ม การที่ 'ลมโกรก' อธิบายสภาพที่มองไม่เห็นในห้อง ซึ่งคล้ายกับสภาพอากาศ",
    tr: "Şemsiyeyi düşünün. 'Esinti olması' odadaki görünmez bir durumu, hava durumu gibi bir şeyi tanımlar.",
    uk: "Подумайте про Парасольку. Те, що «протяг», описує невидимий стан у кімнаті, чимось схожий на погоду.",
    ur: "چھتری کے بارے میں سوچیں۔ کہ 'ہوا چل رہی ہے' کمرے میں ایک غیر مرئی حالت کو بیان کرتا ہے، کچھ حد تک موسم کی طرح۔",
    vi: "Hãy nghĩ về cái Ô. Rằng 'có gió lùa' mô tả một điều kiện vô hình trong phòng, hơi giống thời tiết.",
    zh: "想想雨伞。说“有穿堂风”描述了房间里一种看不见的情况，有点像天气。"
  },
  "Rigtigt! ☂️ Paraply: Vi taler om en generel, usynlig tilstand (at vinden trækker ind). Det fungerer præcis som når vi beskriver vejret.": {
    da: "Rigtigt! ☂️ Paraply: Vi taler om en generel, usynlig tilstand (at vinden trækker ind). Det fungerer præcis som når vi beskriver vejret.",
    en: "Correct! ☂️ Umbrella: We are talking about a general, invisible condition (that the wind is blowing in). It works exactly as when we describe the weather.",
    de: "Richtig! ☂️ Regenschirm: Wir sprechen über einen allgemeinen, unsichtbaren Zustand (dass der Wind hereinweht). Es funktioniert genau so, wie wenn wir das Wetter beschreiben.",
    ar: "صحيح! ☂️ المظلة: نحن نتحدث عن حالة عامة غير مرئية (تهب الرياح للداخل). إنها تعمل تمامًا كما لو كنا نصف الطقس.",
    es: "¡Correcto! ☂️ Paraguas: Estamos hablando de una condición general e invisible (que el viento sopla). Funciona exactamente igual que cuando describimos el clima.",
    fa: "درسته! ☂️ چتر: ما در مورد یک وضعیت کلی و نامرئی صحبت می کنیم (که باد می وزد). دقیقا مانند زمانی که آب و هوا را توصیف می کنیم کار می کند.",
    ku: "Rast e! ☂️ Sîwan: Em behsa rewşek giştî, nedîtbar dikin (ku ba tê de difûre). Ew tam wekî ku em hewayê vedibêjin kar dike.",
    ne: "सहि हो! ☂️ छाता: हामी सामान्य, अदृश्य अवस्था (हावा बहिरहेको छ) को बारेमा कुरा गर्दैछौं। यसले मौसम वर्णन गर्दा जस्तै काम गर्दछ।",
    ps: "سمه ده! ☂️ چترۍ: موږ د عمومي، نه لیدونکي حالت په اړه خبرې کوو (چې باد په کې روان دی). دا په سمه توګه کار کوي لکه کله چې موږ هوا بیانوو.",
    pt: "Correto! ☂️ Guarda-chuva: Estamos falando de uma condição geral e invisível (que o vento está soprando). Funciona exatamente como quando descrevemos o clima.",
    ru: "Правильно! ☂️ Зонт: Мы говорим об общем, невидимом состоянии (что дует ветер). Это работает точно так же, как когда мы описываем погоду.",
    th: "ถูกต้อง! ☂️ ร่ม: เรากำลังพูดถึงสภาพทั่วไปที่มองไม่เห็น (ที่ลมพัดเข้ามา) ซึ่งทำงานเหมือนกับเวลาที่เราอธิบายสภาพอากาศเลย",
    tr: "Doğru! ☂️ Şemsiye: Genel, görünmez bir durumdan (rüzgarın içeri estiğinden) bahsediyoruz. Hava durumunu tanımladığımız zamanki gibi çalışır.",
    uk: "Правильно! ☂️ Парасолька: Ми говоримо про загальний, невидимий стан (що дме вітер). Це працює точно так само, як коли ми описуємо погоду.",
    ur: "بالکل ٹھیک! ☂️ چھتری: ہم ایک عام، غیر مرئی حالت کے بارے میں بات کر رہے ہیں (کہ ہوا اندر چل رہی ہے)۔ یہ بالکل اسی طرح کام کرتا ہے جب ہم موسم کی وضاحت کرتے ہیں۔",
    vi: "Chính xác! ☂️ Ô: Chúng ta đang nói về một tình trạng chung, vô hình (gió lùa vào). Nó hoạt động chính xác như khi chúng ta mô tả thời tiết.",
    zh: "正确！ ☂️ 雨伞：我们正在谈论一种普遍的、看不见的情况（风吹进来）。这完全和我们描述天气时一样。"
  },
  "Rigtigt! 🎯 Pil: Du fokuserer på den specifikke café og stemningen præcis dér.<br><i>(Tip: 'Det' er også korrekt, hvis du fokuserer på den generelle situation).</i>": {
    da: "Rigtigt! 🎯 Pil: Du fokuserer på den specifikke café og stemningen præcis dér.<br><i>(Tip: 'Det' er også korrekt, hvis du fokuserer på den generelle situation).</i>",
    en: "Correct! 🎯 Arrow: You focus on the specific café and the atmosphere exactly there.<br><i>(Tip: 'Det' is also correct if you focus on the general situation).</i>",
    de: "Richtig! 🎯 Pfeil: Du konzentrierst dich auf das bestimmte Café und die Atmosphäre genau dort.<br><i>(Tipp: 'Det' ist auch richtig, wenn du dich auf die allgemeine Situation konzentrierst).</i>",
    ar: "صحيح! 🎯 السهم: أنت تركز على المقهى المحدد والجو هناك بالضبط.<br><i>(نصيحة: 'Det' صحيح أيضًا إذا كنت تركز على الوضع العام).</i>",
    es: "¡Correcto! 🎯 Flecha: Te enfocas en el café específico y el ambiente exactamente allí.<br><i>(Consejo: 'Det' también es correcto si te enfocas en la situación general).</i>",
    fa: "درسته! 🎯 فلش: شما روی کافه خاص و دقیقاً فضای آنجا تمرکز می کنید.<br><i>(نکته: 'Det' در صورت تمرکز بر وضعیت کلی نیز صحیح است).</i>",
    ku: "Rast e! 🎯 Tîr: Hûn balê dikişînin ser kafeya diyarkirî û tam li wir atmosferê.<br><i>(Serişte: 'Det' jî rast e heke hûn balê bikişînin ser rewşa giştî).</i>",
    ne: "सहि हो! 🎯 तीर: तपाईं विशिष्ट क्याफे र त्यहाँको वातावरणमा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: यदि तपाईं सामान्य अवस्थामा ध्यान केन्द्रित गर्नुहुन्छ भने 'Det' पनि सही छ)।</i>",
    ps: "سمه ده! 🎯 تیر: تاسو په ځانګړي کافې او په سمه توګه فضا تمرکز کوئ.<br><i>(اشاره: 'Det' هم سم دی که تاسو په عمومي وضعیت تمرکز وکړئ).</i>",
    pt: "Correto! 🎯 Seta: Você foca no café específico e na atmosfera exatamente lá.<br><i>(Dica: 'Det' também é correto se você focar na situação geral).</i>",
    ru: "Правильно! 🎯 Стрелка: Вы сосредотачиваетесь на конкретном кафе и атмосфере именно там.<br><i>(Подсказка: «Det» также правильно, если вы сосредотачиваетесь на общей ситуации).</i>",
    th: "ถูกต้อง! 🎯 ลูกศร: คุณเน้นที่ร้านกาแฟเฉพาะและบรรยากาศที่นั่นพอดี<br><i>(คำแนะนำ: 'Det' ก็ถูกต้องเช่นกัน หากคุณเน้นที่สถานการณ์ทั่วไป)</i>",
    tr: "Doğru! 🎯 Ok: Belirli bir kafeye ve tam olarak oradaki atmosfere odaklanıyorsunuz.<br><i>(İpucu: Genel duruma odaklanırsanız 'Det' de doğrudur).</i>",
    uk: "Правильно! 🎯 Стрілка: Ви зосереджуєтесь на конкретному кафе та атмосфері саме там.<br><i>(Підказка: «Det» також правильне, якщо ви зосереджуєтесь на загальній ситуації).</i>",
    ur: "بالکل ٹھیک! 🎯 تیر: آپ مخصوص کیفے اور بالکل وہاں کے ماحول پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Det' بھی صحیح ہے اگر آپ عمومی صورتحال پر توجہ مرکوز کرتے ہیں)۔</i>",
    vi: "Chính xác! 🎯 Mũi tên: Bạn tập trung vào quán cà phê cụ thể và bầu không khí chính xác ở đó.<br><i>(Mẹo: 'Det' cũng đúng nếu bạn tập trung vào tình hình chung).</i>",
    zh: "正确！ 🎯 箭头：您关注特定的咖啡馆和那里的氛围。<br><i>（提示：如果您关注一般情况，“Det”也是正确的）。</i>"
  },
  "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle atmosfære og situation på caféen.<br><i>(Tip: 'Der' er også meget almindeligt, da caféen er et specifikt sted).</i>": {
    da: "Rigtigt! ☂️ Paraply: Du fokuserer på den generelle atmosfære og situation på caféen.<br><i>(Tip: 'Der' er også meget almindeligt, da caféen er et specifikt sted).</i>",
    en: "Correct! ☂️ Umbrella: You focus on the general atmosphere and situation at the café.<br><i>(Tip: 'Der' is also very common as the café is a specific place).</i>",
    de: "Richtig! ☂️ Regenschirm: Du konzentrierst dich auf die allgemeine Atmosphäre und Situation im Café.<br><i>(Tipp: 'Der' ist auch sehr üblich, da das Café ein bestimmter Ort ist).</i>",
    ar: "صحيح! ☂️ المظلة: أنت تركز على الجو العام والوضع في المقهى.<br><i>(نصيحة: 'Der' شائع جدًا أيضًا لأن المقهى مكان محدد).</i>",
    es: "¡Correcto! ☂️ Paraguas: Te enfocas en la atmósfera general y la situación en el café.<br><i>(Consejo: 'Der' también es muy común ya que el café es un lugar específico).</i>",
    fa: "درسته! ☂️ چتر: شما روی فضای کلی و وضعیت کافه تمرکز می کنید.<br><i>(نکته: 'Der' نیز بسیار رایج است زیرا کافه یک مکان خاص است).</i>",
    ku: "Rast e! ☂️ Sîwan: Hûn balê dikişînin ser atmosfer û rewşa giştî ya kafeyê.<br><i>(Serişte: 'Der' di heman demê de pir gelemperî ye ji ber ku kafe cîhek taybetî ye).</i>",
    ne: "सहि हो! ☂️ छाता: तपाईं क्याफेको सामान्य वातावरण र स्थितिमा ध्यान केन्द्रित गर्नुहुन्छ।<br><i>(सुझाव: 'Der' पनि धेरै सामान्य छ किनकि क्याफे एक विशिष्ट ठाउँ हो)।</i>",
    ps: "سمه ده! ☂️ چترۍ: تاسو په عمومي چاپیریال او کیفې کې موقعیت ته پام کوئ.<br><i>(اشاره: 'Der' هم خورا عام دی ځکه چې کیفې یو ځانګړی ځای دی).</i>",
    pt: "Correto! ☂️ Guarda-chuva: Você foca na atmosfera geral e na situação do café.<br><i>(Dica: 'Der' também é muito comum, pois o café é um local específico).</i>",
    ru: "Правильно! ☂️ Зонт: Вы сосредотачиваетесь на общей атмосфере и ситуации в кафе.<br><i>(Подсказка: «Der» также очень распространено, поскольку кафе — это определенное место).</i>",
    th: "ถูกต้อง! ☂️ ร่ม: คุณเน้นที่บรรยากาศทั่วไปและสถานการณ์ที่ร้านกาแฟ<br><i>(คำแนะนำ: 'Der' ก็เป็นเรื่องธรรมดามากเช่นกัน เนื่องจากร้านกาแฟเป็นสถานที่เฉพาะ)</i>",
    tr: "Doğru! ☂️ Şemsiye: Kafedeki genel atmosfere ve duruma odaklanıyorsunuz.<br><i>(İpucu: Kafe belirli bir yer olduğu için 'Der' de çok yaygındır).</i>",
    uk: "Правильно! ☂️ Парасолька: Ви зосереджуєтесь на загальній атмосфері та ситуації в кафе.<br><i>(Підказка: «Der» також дуже поширене, оскільки кафе – це конкретне місце).</i>",
    ur: "بالکل ٹھیک! ☂️ چھتری: آپ کیفے میں عمومی ماحول اور صورتحال پر توجہ مرکوز کرتے ہیں۔<br><i>(ٹپ: 'Der' بھی بہت عام ہے کیونکہ کیفے ایک مخصوص جگہ ہے)۔</i>",
    vi: "Chính xác! ☂️ Ô: Bạn tập trung vào bầu không khí chung và tình hình tại quán cà phê.<br><i>(Mẹo: 'Der' cũng rất phổ biến vì quán cà phê là một địa điểm cụ thể).</i>",
    zh: "正确！ ☂️ 雨伞：您关注咖啡馆的一般氛围和情况。<br><i>（提示：“Der”也很常见，因为咖啡馆是一个特定的地方）。</i>"
  },
  "Tænk på Pilen. Vi zoomer ind på en bestemt placering (køleskabet) og kigger på en fysisk ting (kagen).": {
    da: "Tænk på Pilen. Vi zoomer ind på en bestemt placering (køleskabet) og kigger på en fysisk ting (kagen).",
    en: "Think of the Arrow. We zoom in on a specific location (the fridge) and look at a physical thing (the cake).",
    de: "Denke an den Pfeil. Wir zoomen auf einen bestimmten Ort (den Kühlschrank) und betrachten eine physische Sache (den Kuchen).",
    ar: "فكر في السهم. نقوم بالتكبير على موقع معين (الثلاجة) وننظر إلى شيء مادي (الكعكة).",
    es: "Piensa en la Flecha. Hacemos zoom en una ubicación específica (el refrigerador) y miramos una cosa física (el pastel).",
    fa: "به فلش فکر کنید. روی یک مکان خاص (یخچال) زوم می کنیم و به یک چیز فیزیکی (کیک) نگاه می کنیم.",
    ku: "Tîrê bifikirin. Em li cîhek diyarkirî (sarinc) nêzîk dibin û li tiştek fîzîkî (kek) dinêrin.",
    ne: "तीरको बारेमा सोच्नुहोस्। हामी एक विशिष्ट स्थान (फ्रिज) जुम इन गर्छौं र भौतिक कुरा (केक) हेर्छौं।",
    ps: "د تیر په اړه فکر وکړئ. موږ یو ځانګړي ځای (ریفریجریټر) زوم کوو او فزیکي شی (کیک) ته ګورو.",
    pt: "Pense na Seta. Damos um zoom em um local específico (a geladeira) e olhamos para uma coisa física (o bolo).",
    ru: "Подумайте о Стрелке. Мы приближаем определенное место (холодильник) и смотрим на физическую вещь (торт).",
    th: "นึกถึงลูกศร เราซูมเข้าไปที่ตำแหน่งเฉพาะ (ตู้เย็น) และดูที่สิ่งของทางกายภาพ (เค้ก)",
    tr: "Oku düşünün. Belirli bir konuma (buzdolabına) odaklanıyoruz ve fiziksel bir nesneye (pastaya) bakıyoruz.",
    uk: "Подумайте про Стрілку. Ми збільшуємо певне місце (холодильник) і дивимося на фізичну річ (торт).",
    ur: "تیر کے بارے میں سوچیں۔ ہم ایک مخصوص مقام (فریج) پر زوم ان کرتے ہیں اور ایک جسمانی چیز (کیک) کو دیکھتے ہیں۔",
    vi: "Hãy nghĩ về Mũi tên. Chúng tôi phóng to một vị trí cụ thể (tủ lạnh) và nhìn vào một vật thể vật lý (chiếc bánh).",
    zh: "想想箭头。我们放大特定位置（冰箱）并观察物理事物（蛋糕）。"
  },
  "Rigtigt! 🎯 Pil: Vi peger på en fysisk ting (kagen) på en helt specifik placering (i køleskabet).": {
    da: "Rigtigt! 🎯 Pil: Vi peger på en fysisk ting (kagen) på en helt specifik placering (i køleskabet).",
    en: "Correct! 🎯 Arrow: We point to a physical thing (the cake) in a very specific location (in the fridge).",
    de: "Richtig! 🎯 Pfeil: Wir weisen auf eine physische Sache (den Kuchen) an einem ganz bestimmten Ort (im Kühlschrank) hin.",
    ar: "صحيح! 🎯 السهم: نحن نشير إلى شيء مادي (الكعكة) في مكان محدد للغاية (في الثلاجة).",
    es: "¡Correcto! 🎯 Flecha: Señalamos una cosa física (el pastel) en una ubicación muy específica (en el refrigerador).",
    fa: "درسته! 🎯 فلش: ما به یک چیز فیزیکی (کیک) در یک مکان بسیار خاص (در یخچال) اشاره می کنیم.",
    ku: "Rast e! 🎯 Tîr: Em tiştekî fizîkî (kek) li cîhekî pir diyar (di sarincokê de) nîşan didin.",
    ne: "सहि हो! 🎯 तीर: हामी एक धेरै विशिष्ट स्थान (फ्रिजमा) मा एक भौतिक कुरा (केक) लाई संकेत गर्छौं।",
    ps: "سمه ده! 🎯 تیر: موږ په یو خورا مشخص ځای کې (په فریج کې) یو فزیکي شی (کیک) ته اشاره کوو.",
    pt: "Correto! 🎯 Seta: Apontamos para uma coisa física (o bolo) em um local muito específico (na geladeira).",
    ru: "Правильно! 🎯 Стрелка: Мы указываем на физическую вещь (торт) в очень конкретном месте (в холодильнике).",
    th: "ถูกต้อง! 🎯 ลูกศร: เราชี้ไปที่สิ่งของที่จับต้องได้ (เค้ก) ในตำแหน่งที่เฉพาะเจาะจงมาก (ในตู้เย็น)",
    tr: "Doğru! 🎯 Ok: Çok belirgin bir konumdaki (buzdolabındaki) fiziksel bir nesneye (pastaya) işaret ediyoruz.",
    uk: "Правильно! 🎯 Стрілка: Ми вказуємо на фізичну річ (торт) у дуже конкретному місці (у холодильнику).",
    ur: "بالکل ٹھیک! 🎯 تیر: ہم ایک بہت ہی مخصوص جگہ (فریج میں) ایک جسمانی چیز (کیک) کی طرف اشارہ کرتے ہیں۔",
    vi: "Chính xác! 🎯 Mũi tên: Chúng tôi chỉ vào một vật thể vật lý (chiếc bánh) ở một vị trí rất cụ thể (trong tủ lạnh).",
    zh: "正确！ 🎯 箭头：我们指向一个非常特定位置（冰箱里）的实物（蛋糕）。"
  },
  "Start øvelse!": {
    da: "Start øvelse!",
    en: "Start exercise!",
    de: "Übung starten!",
    ar: "ابدأ التمرين!",
    es: "¡Iniciar ejercicio!",
    fa: "شروع تمرین!",
    ku: "Xebatê dest pê bikin!",
    ne: "अभ्यास सुरु गर्नुहोस्!",
    ps: "تمرین پیل کړئ!",
    pt: "Iniciar exercício!",
    ru: "Начать упражнение!",
    th: "เริ่มแบบฝึกหัด!",
    tr: "Egzersize başla!",
    uk: "Почати вправу!",
    ur: "مشق شروع کریں!",
    vi: "Bắt đầu bài tập!",
    zh: "开始练习！"
  }
};

const blockMatch = content.match(/export const translations = \{([\s\S]*?)\n\};/);
if (blockMatch) {
    let newContent = content;
    
    // We will append to each language object.
    const langs = ['da', 'en', 'de', 'ar', 'es', 'fa', 'ku', 'ne', 'ps', 'pt', 'ru', 'th', 'tr', 'uk', 'ur', 'vi', 'zh'];
    
    langs.forEach(lang => {
        let replacementBlock = "";
        for (const [key, langsMap] of Object.entries(t)) {
            const transText = langsMap[lang] || langsMap['en']; // fallback to en if somehow missing
            replacementBlock += "    \"" + key.replace(/"/g, '\\"') + "\": \"" + transText.replace(/"/g, '\\"') + "\",\n";
        }
        
        const langRegex = new RegExp("  " + lang + ": \\{\\n");
        newContent = newContent.replace(langRegex, "  " + lang + ": {\n" + replacementBlock);
    });
    
    fs.writeFileSync(file, newContent, 'utf8');
    console.log("Translations successfully injected!");
} else {
    console.log("Could not parse translations file");
}
